### ISSUE TITLE
Whatsapp disconnects bot every day, bot doesn't try to reconnect

### ISSUE THREAD

**Issue by Arkanista** [FKLC/WhatsAppToDiscord#10]
![9LCqi7n](https://user-images.githubusercontent.com/68946052/89098404-9b9ec080-d3e7-11ea-81e7-f33a209efb84.png)
Every day  whatsapp seems to disconnect my session, and the bot doesn't try to reconnect and just stops without closing the proccess. I am sure i didn't lose connection,

**Comment by FKLC** [comment]
I couldn't reproduce the error but the latest release should fix it. If it is still not working feel free to reopen the issue.

**Comment by Arkanista** [comment]
I am experiencing the same issue on the new version. Albeit the errors is displayed in new line.

**Comment by FKLC** [comment]
Welp, I handled for wrong error but now the latest release should work!
