### ISSUE TITLE
Is WA2DC.exe safe to download?

### ISSUE THREAD

**Issue by DotSlash-A** [FKLC/WhatsAppToDiscord#100]
I was experimenting with discord bots so landed here!
when I try downloading the .exe file, my anti-virus says it is infected with something(screengrab is below). Could you please confirm if it is safe to download?

![image](https://user-images.githubusercontent.com/91440435/188049663-9fe8772f-cbf7-45e8-bd21-0a676ce4e6a3.png)

**Comment by magadan** [comment]
Pls, read: [https://fklc.github.io/WhatsAppToDiscord/#/faq?id=flagged-as-a-virus](https://fklc.github.io/WhatsAppToDiscord/#/faq?id=flagged-as-a-virus)

**Comment by FKLC** [comment]
Yeah, as @magadan said, I don't put viruses to executables (you don't have to trust me), and you are always welcome to clone the project and run it yourself. I'm closing the issue as it is already mentioned on FAQ of documentation.
