### ISSUE TITLE
No Commands Work

### ISSUE THREAD

**Issue by kiwuthegamer** [FKLC/WhatsAppToDiscord#102]
All commands result in the bot saying "Unknown command: `Type help` to see available commands"
(Typing "help" also results in the same message)

**Comment by calbinson** [comment]
I have the same exact issue

**Comment by lryjnks** [comment]
yeah same here

**Comment by FKLC** [comment]
can any of you send their logs.txt?

**Comment by lryjnks** [comment]
I start the server, delete the logs so that there is not too much information inside. As soon as I send the commands I get in Discord only "Unknown command: `Type help` to see available commands".

The logs are empty.


OS: Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-47-generic x86_64)

**Comment by lryjnks** [comment]
It does not load the message content

_Line 237-240_ discord_manager.js 
 ```js
   },
  unknownCommand: async (message) => {
    controlChannel.send(`Unknown command: \`${message.content}\`\nType \`help\` to see available commands`);
  },  
```
  
 
![discord](https://user-images.githubusercontent.com/33368776/189273509-84275cc2-b90a-44cb-b6c3-1f434be3f1c7.png)

**Comment by lryjnks** [comment]
_logs.txt_

´´´
{"level":30,"time":1662699983357,"pid":239006,"hostname":"srvlnx01","msg":"Starting"}
{"level":30,"time":1662699983358,"pid":239006,"hostname":"srvlnx01","msg":"Update checked."}
{"level":30,"time":1662699983374,"pid":239006,"hostname":"srvlnx01","msg":"Initialized database."}
{"level":30,"time":1662699983378,"pid":239006,"hostname":"srvlnx01","msg":"Loaded settings."}
{"level":30,"time":1662699983380,"pid":239006,"hostname":"srvlnx01","msg":"Loaded contacts."}
{"level":30,"time":1662699983382,"pid":239006,"hostname":"srvlnx01","msg":"Loaded chats."}
{"level":30,"time":1662699984124,"pid":239006,"hostname":"srvlnx01","msg":"Discord client started."}
{"level":30,"time":1662699984742,"pid":239006,"hostname":"srvlnx01","msg":"Repaired channels."}
{"level":30,"time":1662699984854,"pid":239006,"hostname":"srvlnx01","msg":"WhatsApp client started."}
{"level":30,"time":1662699984948,"pid":239006,"hostname":"srvlnx01","browser":["Baileys","Chrome","4.0.0"],"helloMsg":{"clientHello":{"ephemeral":"kc51ssu1mspfSY3uTTQiFmuROKkv2uQ4OXempxzulUA="}},"msg":"connected to WA Web"}
{"level":30,"time":1662699985017,"pid":239006,"hostname":"srvlnx01","node":{"username":"491745484143","passive":true,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2230,"tertiary":15},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","device":11},"msg":"logging in..."}
{"level":30,"time":1662699985450,"pid":239006,"hostname":"srvlnx01","msg":"20 pre-keys found on server"}
{"level":30,"time":1662699985489,"pid":239006,"hostname":"srvlnx01","msg":"opened connection to WA"}
{"level":30,"time":1662699985643,"pid":239006,"hostname":"srvlnx01","msg":"handled 0 offline messages/notifications"}

´´´

Discord Commands:

![image](https://user-images.githubusercontent.com/33368776/189275984-88c6e34b-2969-4813-b14f-00f22cc5c8ec.png)

**Comment by meduard10** [comment]
I have the same issue, Ubuntu 22.04

**Comment by KungFuCookie** [comment]
Hey I know discord changed the way commands are handled recently because another bit integration also started to fail.

Can you try using /raw command

**Comment by lryjnks** [comment]
Hmm.. still not working

![image](https://user-images.githubusercontent.com/33368776/189501697-9e75b58c-db31-4887-9981-d11714245397.png)

**Comment by Heath123** [comment]
Fix: enable this setting in your bot settings in https://discord.com/developers/applications/
![image](https://user-images.githubusercontent.com/13787163/189504154-f26a8172-2304-46ea-ae1c-cdaaf8ad40de.png)

**Comment by FKLC** [comment]
> Fix: enable this setting in your bot settings in https://discord.com/developers/applications/ ![image](https://user-images.githubusercontent.com/13787163/189504154-f26a8172-2304-46ea-ae1c-cdaaf8ad40de.png)

This seems like the fix. Thanks for finding it out @Heath123. I also thought about it being about the intents, but looked only at the code. Thanks again. I will update the FAQ shortly, and closing the issue.
