### ISSUE TITLE
Starting as systemd service

### ISSUE THREAD

**Issue by Max-Trueby** [FKLC/WhatsAppToDiscord#103]
Hi,
I have the following issue:
I'm trying to make the bot to autostart on boot. But then it always crashes, since you need to enter the Token in the commandline manually.
And after I run the bot normally, then the token doesn't save in the db.
Is there a option that I can save the token, so I can start the bot on boot with sytemd?

Max

**Comment by FKLC** [comment]
I mean I guess you can manually create the database, but it would be time consuming, and if it can't save to db, your chats will disappear (will be moved out of the category) after running the bot. You can try sending your logs. Also, make sure the bot has writing permission. For example on Heroku this is an issue.

**Comment by magadan** [comment]
Options:

1 - Use "supervisord" for a compiled version to start.

 2 - If you use a source version with npm install, you can use pm2

npm install pm2 -g

Go to the dist compiled directory and

pm2 start . --name WhatsAppToDiscord

pm2 save

pm2 startup

**Comment by KungFuCookie** [comment]
Hey I used pm2 start with the compiled Linux version
