### ISSUE TITLE
control-room not created

### ISSUE THREAD

**Issue by DotSlash-A** [FKLC/WhatsAppToDiscord#104]
I am new to this so I have followed the exact procedure specified in 'Setup Steps'.
I have successfully followed till step-11 where I have authorized the bot to the server.
but in the next step i.e step 12, the bot has joined my server but it did not create any channels. So could you please help me with how to create the '#control-room' channel to generate the QR code?

Follow the exact procedure mentioned in the Setup guide, and add the bot to the server.
2. error: the 'control-room' channel is not being created automatically.

**Platform**
 -  Windows.
 
![image](https://user-images.githubusercontent.com/91440435/189662315-71ab4253-30c7-488a-bc3b-af409059ff2c.png)

**Comment by DotSlash-A** [comment]
yes, I've given the bot permission to manage channels.

I am new to this, could you tell me how to identify if the bot has crashed?
 could you also pls tell me how to get logs.txt?

**Comment by FKLC** [comment]
> I am new to this, could you tell me how to identify if the bot has crashed?

The file you downloaded, WA2DC, would be no longer running, and the bot would be offline like this 
![image](https://user-images.githubusercontent.com/29578493/189707620-ccfdcc1c-141e-46bf-9507-6b29d69add61.png)



> could you also pls tell me how to get logs.txt?

Your folder should look like this ![image](https://user-images.githubusercontent.com/29578493/189707881-ee1b977e-8c84-458a-a987-9fda7802a0e2.png) 
and as you see it is at the same place as the file you downloaded.

**Comment by DotSlash-A** [comment]
yes, the bot crashed.
[logs.txt](https://github.com/FKLC/WhatsAppToDiscord/files/9550061/logs.txt)

**Comment by FKLC** [comment]
It is in the same folder as the bot. Simply right click and delete/move to trash.
![image](https://user-images.githubusercontent.com/29578493/191576772-95bc7cd2-1e26-47eb-886b-42cd216b3437.png)

**Comment by FKLC** [comment]
Closing the issue due to inactivity.
