### ISSUE TITLE
Polished instructions

### ISSUE THREAD

**Issue by 3dkfi** [FKLC/WhatsAppToDiscord#105]
We are trying to implement your great code into Raspberry pi 2 and it seems to build to it. But we are now little baffled how can we start the script without doing the install_script route every time we boot the system.

You have a good instructions for Windows but how about linux? It would be a nice addition :) or at least include note for linux users how to add this script to run in system startup.

We were also wondering if this is raspberry pi 2 friendly in reality? It seems to build but collegue said by the documents it will most likely not work correctly so having a documentation about it working or not working on raspberry pi's would be a good addition! :)

For additional content:
This projects seems quite nice and we are eager to get this system running in our Hacklab!

**Comment by spookycookie27** [comment]
personally I use PM2 on a linux VM, you will need to install it.

Then its as simple as a single command `pm2 start WA2DC-Linux` 

I think you can also set pm2 to start services automaticallay on reboot/startup

you can refer to this thread where it was also discussed recently 
https://github.com/FKLC/WhatsAppToDiscord/issues/103

**Comment by FKLC** [comment]
Thank you for your kind words, and thanks @spookycookie27 for helping them quickly. As @spookycookie27 said, you can use pm2 to run the compiled version. Assuming your raspberry pi doesn't delete files after a reboot, you should also be able to run the bot using the command @spookycookie27 provided. To run on restart, run `pm2 startup` and follow instructions, then run `pm2 save`. AFAIK, this should be enough.

**Comment by FKLC** [comment]
Closing the issue due to inactivity.
