### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by shad-yx** [FKLC/WhatsAppToDiscord#106]
Is there any way we could sync groups with this?

**Comment by FKLC** [comment]
Yes, is it for personal use or to bridge a community between whatsapp and discord? If it is for personal use, then just simply follow the [setup instructions](https://fklc.github.io/WhatsAppToDiscord/#/setup) and it will work. If you want to use it on a public server, i.e. your school group, run the setup as usual, then check out this [FAQ point](https://fklc.github.io/WhatsAppToDiscord/#/faq?id=can-i-use-this-bot-on-a-public-server) to make sure you don't expose your whole WhatsApp with others.

**Comment by shad-yx** [comment]
@FKLC Hi, I managed to get groups working but my bot suddenly stopped and every time I relaunch it to make it go online, it says that I'm running it for the first time and asks for a new token, and returns a new link for the invite. is there anywhere I could DM you personally? I just have a couple more questions regarding the bot.

**Comment by FKLC** [comment]
Unfortunately, this is the only way to contact me. what you are describing sounds like the bot crashes for some reason and doesn't save it's status at exit, hence requiring you to enter the token every time. You can share your logs.txt and I can take a look at it. In the meantime maybe try deleting storage.db and rerunning the bot. If that doesn't help send your logs and I'll try to fix the issue.
