### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by peanutlasko** [FKLC/WhatsAppToDiscord#108]
Any chance this would get a docker container? Would be useful to run as a container on my homelab.

**Comment by Nerodacles** [comment]
It would be much appreciated!

**Comment by FKLC** [comment]
it exists now, though it is pretty simple and I'm not sure if that's what you asked for.

**Comment by hipur** [comment]
Instead of providing a Dockerfile for us to build the image, you could build it and upload to dockerhub. Thus providing only a link or a docker-compose.yaml file where the user can set the ENV token when deploying.
