### ISSUE TITLE
Interactive Messages

### ISSUE THREAD

**Issue by HClausing** [FKLC/WhatsAppToDiscord#109]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
The possibility of sending interactive messages to WhatsApp, like in the WhatsApp Bussiness API (with button, list, etc), from Discord.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by FKLC** [comment]
Unfortunately, I won't implement this. I'm aware of these features, but I'm worried that the use of these functions may get people banned. Also, as you said, these features aren't intended for personal WhatsApp accounts, so unfortunately, I will have to refuse this feature request. Thanks for your contribution.

**Comment by HClausing** [comment]
Thanks for your quick answer.

No problem, I see your point.

Best regards.
