### ISSUE TITLE
Work as Windows Service or Scheduled Task

### ISSUE THREAD

**Issue by HClausing** [FKLC/WhatsAppToDiscord#110]
**Is your feature request related to a problem? Please describe.**
Not really, maybe it's a new feature.

**Describe the solution you'd like**
I've tried to create a scheduled task on m company's server to start the WA2DC.exe on starts (without any user logged). The application starts and creates a process ID, but didn't connects the Bot on discord, neither writes anything on log.

I really don't know if it's waiting for a token. Tried with many server users: My own account, administrator, system,etc.

Maybe working as windows service could it works? I'm a donet dev and don't know anything about this project framework (I guess it's node.js) and don't figure how to create a windows service that hosts this app.

Can you help me on this?

**Describe alternatives you've considered**
I've read some articles on the internet about services and scheduled tasks, but didn't found anything relevant.

**Additional context**
Thanks

**Comment by HClausing** [comment]
Yes, running the .exe from my user logged on server (from terminal services), it works fine (without requesting the token again), but on scheduled tasks I can't see any error on logs.txt. The process is visible on Task Manager, but the BOT won't go online on discord server.

Everything works fine if I manually run the .exe from my logged user on server. I'm trying just to automate the execution without having any user logged.

**Comment by spookycookie27** [comment]
I think there is an option to click saying 'run even when user is not logged in' , have you tried this?
Ill connect to my work vpn and send you some screenshots if you think it will help.

**Comment by HClausing** [comment]
> I think there is an option to click saying 'run even when user is not logged in' , have you tried this? Ill connect to my work vpn and send you some screenshots if you think it will help.
> 
> And it works fine running the exe from commaind line yeah?
> 
> this is same user (kungfu Cookie) , i have 2 github accounts

Actually I already tried this way ("run even when user is not logged in").

Running from command line it works also.

![image](https://user-images.githubusercontent.com/15158923/194972658-db56e905-3e02-4556-bc17-2c5242d1966c.png)

![image](https://user-images.githubusercontent.com/15158923/194972560-c2c957d4-25b3-4a27-a3c1-fe2cb0c4dfb3.png)

Thanks for the help. I'll try a bit more from scheduled tasks, I think it should work.

**Comment by KungFuCookie** [comment]
is the command being run from the task action - to a fully qualified path?

like c://some/pathWA2DCFolder/WA2DC.exe

I agree I think it should work, your VM works manually, so should also work when kicked off via a task.
In the windows event log, you should find a trace of the task failing I think
