### ISSUE TITLE
Whatsapp to Discord crashing after running for 3 - 4 days continuously

### ISSUE THREAD

**Issue by mastanoob** [FKLC/WhatsAppToDiscord#112]
**Describe the bug**
The server end ups crashing after 3 - 4 days of continuous up time. This is the second time this issue has occurred. The thing to note is that we are hitting more then 100+ chats on our server and would still receive error: "Maximum number of channels in category reached (50)", after which the server would crash.  

**To Reproduce**
1. run the server 
2. have +100 chats
3. See error

**Expected behavior**
After the enhancement you implemented the server should be able to handle more then +100 channels and not crash.

**Logs**
see the attached logs.txt
[logs.txt](https://github.com/FKLC/WhatsAppToDiscord/files/9801372/logs.txt)

**Platform**
 - OS: [Linux]

**Additional context**
- running on node.js server.
- ran the server without shutdown for more then 3 - 4 days.
- over the period of 3 - 4 days uptime; new chats would be started.

**Comment by stnKrisna** [comment]
Current workaround is to start the bot using this command:
`while true; do ./WA2DC; sleep 2; done`

**Comment by FKLC** [comment]
This should be fixed now. Please check the new version. Thank you!
