### ISSUE TITLE
I wanna have 2 bots active

### ISSUE THREAD

**Issue by Maxdadlink** [FKLC/WhatsAppToDiscord#113]
**i wanna have 2 bots active but i dont know why one in a while just it's closed so i got one for me to my real number and another one to a server to conect a chat with a server okay? but it's a different number**
then i dont know if it's cause it's the same program whatever it's close in a while

idk about this topic but if u cant do it it's okay

**Comment by FKLC** [comment]
unfortunately I don't think this is possible due to the program I use to build the executable.
