### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by Maxdadlink** [FKLC/WhatsAppToDiscord#114]
can u make a conecction between the status of discord and whatsapp 
like 
if i got my state in discord like idk "chill" or "busy" whatever  it changes too in my whatsapp 
it's just a idea

u can do it with a command or something

**Comment by FKLC** [comment]
This is a good idea but I'm trying to keep the bot very basic. Even in its current form, I'm struggling to keep it working. This would introduce new stuff to keep track of. So, unfortunately, I'll have to reject this.
