### ISSUE TITLE
the bot doesn't detect some people

### ISSUE THREAD

**Issue by Maxdadlink** [FKLC/WhatsAppToDiscord#117]
i got a discord server connect with a wsp group and the bot when some people (exactly 2) from whatsapp send messages it doesnt appear in discord like every message many people talk there so they are the issue

idk if it's the bot or something about them, can u check it? 
thaaanks

**Comment by Shinobi7k** [comment]
I have the same issue. But I noticed that the one that the bot doesn't detect disabled the "online" status when he is online. I don't know if this is related or not.

**Comment by FKLC** [comment]
I don't know what might be causing this but closing this issue for now as I released a new update, please see if it works and reopen if needed.
