### ISSUE TITLE
raspberry pi

### ISSUE THREAD

**Issue by jacklolidk** [FKLC/WhatsAppToDiscord#119]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
a version of this for the raspberry pi

**Describe alternatives you've considered**
not using this
(not worked)

**Additional context**
no

**Comment by rodrigopar99** [comment]
This is working just fine, idk what you are talking about lol

**Comment by jacklolidk** [comment]
"binary exec error"

**Comment by jacklolidk** [comment]
-bash: ./WA2DC-Linux: cannot execute binary file: Exec format error

**Comment by Heath123** [comment]
Try running ti from source? A binary ARM build would be nice though, for me I want it to run this on an Oracle Free Tier VM

**Comment by jacklolidk** [comment]
having issues running it

**Comment by TukangM** [comment]
for now arm deviec or other arch can use box64 https://github.com/ptitSeb/box64 to run x64 amd on other arch

**Comment by Heath123** [comment]
> for now arm deviec or other arch can use box64 https://github.com/ptitSeb/box64 to run x64 amd on other arch

That seems like a very inefficient and complicated way to do it when you can just run it from the source code directly (I’m doing that and it works fine)

**Comment by FKLC** [comment]
Please note that "compiling" for JS doesn't really exist. sure we can minify code and etc. but with current "compilation" method, pkg, it is probably slower to run the binary. if you want you can use Docker, but that uses node as well, so doesn't really matter. Since I can't compile for raspberry, I'm closing the issue.

**Comment by Heath123** [comment]
> Since I can't compile for raspberry

You can probably cross compile but that might be a bit of a pain

**Comment by FKLC** [comment]
I can't cross compile because of sqlite. it is a native module and requires to run on the platform itself.

**Comment by TukangM** [comment]
just run index.js from ./src/index.js

**Comment by FKLC** [comment]
Can someone here try the latest arm builds?

**Comment by MalurixGaming** [comment]
work :D yeah
