### ISSUE TITLE
Supporting Discord Edits

### ISSUE THREAD

**Issue by TheAnimatrix** [FKLC/WhatsAppToDiscord#122]
An experimental feature can be added where if you edit the discord message, it detects this edit and replies to your previous erroneous whatsapp message with the newer message + an edited flag like (edited, *). Instead of replying with the entire new message just the difference of the old and new can be sent as well as the reply

for example 

You : Yo did you try whutaspp discord bor ?

Edit :

Yo did you try whatsapp discord bro ? - In discord

what's sent :
Reply
> You : Yo did you try whutsapp discord bor?

Whatsapp* bro*
(or)
Yo did you try whatsapp discord bro ? - edited

**Comment by FKLC** [comment]
This is a good idea, but as with the other issue I just closed, this just adds another layer of complexity. This project is already too hard to maintain and while this is a good idea, it isn't going to affect the user experience in a massive way. If this feature was implemented on whatsapp web, I would have considered adding this, but unfortunately, I'll have to reject this
