### ISSUE TITLE
more than 50 channels not supported

### ISSUE THREAD

**Issue by theassemblerguy** [FKLC/WhatsAppToDiscord#123]
So after I sent a merry Christmas to all of my 384 contacts., the bot broke. It never got past the stage where it said it skips auto update as I ran it with node. Then I took a look at the log , where I found this:
"Invalid Form Body\nparent_id: Maximum number of channels in category reached (50)"}
So well, it seems like the bot forcefully dies after you get more than 50 chats in WhatsApp. Maybe you’d like to remove the category by default and just create the channels plainly in the server? From what I’ve now read within the Discord docs, this shall bump the limit up to 500.

**Comment by FKLC** [comment]
If you still haven't abandoned the project... please try again and see if it works.
