### ISSUE TITLE
Update from Discord Bots/Webhook not Appearing in Whatsapp. 

### ISSUE THREAD

**Issue by ubAI6689** [FKLC/WhatsAppToDiscord#124]
Apparently not every message from Discord bots/webhook will be synced to WhatsApp. The only bot that is working for me so far is IFTTT bot. I have tried Mee6, also created my own Webhook to fetch my tweet, work on Discord but not appearing on WhatsApp. Is there any work around?

**Comment by firdaussoberi** [comment]
I can vouch that the plain webhook integration with discord simply didn't work. I tried a different way, this time using discord.py as so:

```
import os
import discord
import asyncio


TOKEN = "sometoken"
GUILD = ""
channel_id = "someid"

def sendMessage(message):
    #client = discord.Client()
    client = discord.Client(intents=discord.Intents.default())
    @client.event
    async def on_ready():


        channel = client.get_channel(int(channel_id))
        await channel.send(message)
        print("done")

        return ""


    client.run(TOKEN)
    print("end")


if __name__ == '__main__':

    sendMessage("abc")
```

this one works and seems to send the message to whatsapp. I'm thinking, does it has to do with the web-socket way the packages are written?

**Comment by firdaussoberi** [comment]
I think the type of the webhook also plays a role here (not sure why)

<img width="1036" alt="Screenshot 2023-01-05 at 20 46 10" src="https://user-images.githubusercontent.com/8426299/210876712-b11b5229-a015-46d4-a82e-8928d1d6f92b.png">

For example, incoming webhook don't work when the bot posts into channel. Application webhook works fine and sync to whatsapp (if i use some discord.py script to emulate sending a message to a discord channel).

**Comment by firdaussoberi** [comment]
Oh and the Embed object in discord (I just realized this) does not really work either. 
I managed to replicate this by this script, from:

```
import os

import discord

TOKEN = "sometoken"
GUILD = "somegroupname"
channel_id = "somechannelid"

#client = discord.Client()
#client = discord.Client(intents=discord.Intents.default())
intents = discord.Intents.default()
intents.message_content = True
client = discord.Client(intents=intents)


@client.event
async def on_ready():
    for guild in client.guilds:
        if guild.name == GUILD:
            break

    print(
        f'{client.user} is connected to the following guild:\n'
        f'{guild.name}(id: {guild.id})\n'
    )

    members = '\n - '.join([member.name for member in guild.members])
    print(f'Guild Members:\n - {members}')

@client.event
async def on_message(message):

    if message.author == client.user:
        return ""

    msg=message.content

    if not message.attachments:
        if message.embeds:
            print("EMB")
            print(message.author, message.embeds[0])
            await message.channel.send(embed=message.embeds[0])
        else:
            print("MSG")
            print(message.author, message.content)
            await message.channel.send(msg)            
    else:
        print("ATT")
        print(message.author, message.attachments)    
        await message.channel.send(msg)        
    print("done")
    return ""


client.run(TOKEN)
```

I should probably open this as separate issue, with `Enhancement` label.

**Comment by FKLC** [comment]
This is expected and won't be fixed. Sorry.
