### ISSUE TITLE
Discord to whatsapp person identification

### ISSUE THREAD

**Issue by bomxacalaka** [FKLC/WhatsAppToDiscord#125]
**Is your feature request related to a problem? Please describe.**

Always frustrated when anyone can send a message on discord group but it will be sent as one bot on whatsapp. No way of knowing who sent that message.

**Describe the solution you'd like**

Simplest solution though not perfect would be to add a "<discord sender's name>: <discord to whatsapp message>" to the beginning of the message. So when Joe sends "Hello world" on discord, when the message reaches whatsapp it will be displayed as "Joe: Hello world".

**Describe alternatives you've considered**

More complex solution isnt really required as long as others would be able to mess in any way. That said if possible you could add some sort of sticker of the discord profile of the sender along with their nickname in the beginning of the message. So whatsapp will receive: "<discord sender's sticker><discord sender's name>: <message>".

**Additional context**
Nothing to add.

**Comment by FKLC** [comment]
Have you tried [enableDCPrefix](https://fklc.github.io/WhatsAppToDiscord/#/commands?id=enabledcprefix) option?

**Comment by bomxacalaka** [comment]
I feel like a fool now lol, thanks a lot.
