### ISSUE TITLE
Problem with running the File on Mac

### ISSUE THREAD

**Issue by StringaBall** [FKLC/WhatsAppToDiscord#126]
I know this is not really a bug but I fairly new to this and still a huge noob. I downloaded the MacOS file and tried to open it which it automatically does with TextEditor. So I googled and tried a different commands in the Terminal to run it as a shell script. I always get the message "cannot execute binary file" Could anyone be so kind and guide me towards the correct way of running it:)

**Platform**
 - OS: MacOS
 - 
**Additional context**

**Comment by spookycookie27** [comment]
hi you need to use the terminal to give permissions to it, (one time only) before running it 

sudo chmod +x ./WA2DC-mac (or whatever the file is called)

and then try to run with ./WA2DC-mac

**Comment by spookycookie27** [comment]
as this is your 1st time ever some of the steps above wont be relevant.

**Comment by StringaBall** [comment]
thank you very much for your help it worked!

**Comment by spookycookie27** [comment]
awesome! - cold you close the issue?

**Comment by StringaBall** [comment]
ok just one more thing. if i close discord and reopen it the bot seems to be offline- is that  what u mean with the reauthorize measure u described up there?

**Comment by StringaBall** [comment]
<img width="353" alt="Bildschirm­foto 2023-02-15 um 09 56 38" src="https://user-images.githubusercontent.com/124082126/218980586-0b0c62f6-67c4-41c4-8a89-62818c84e629.png">

ok then it happened when i shut down my mac but he is definitely offline as you can see in the picture

**Comment by FKLC** [comment]
> and then try to run with ./WA2DC-mac

You have to redo this step each time you want to use the bot. Not the chmod step, but `./WA2DC-mac` part

**Comment by StringaBall** [comment]
ah ok that's what i thought thanks dude!:)
