### ISSUE TITLE
Whatsapp can't read the QR code

### ISSUE THREAD

**Issue by Johanndw9** [FKLC/WhatsAppToDiscord#127]
When I scan the QR code with whatsapp it says " Couldn't link device try again later"

**Comment by spakecdk** [comment]
Same. Seems like the project will not be updated considering the activity :(

**Comment by FKLC** [comment]
It is not that abandoned the project completely but I really don't have any time for my personal projects due to university work. I'm sorry for not maintaining the project.

**Comment by spakecdk** [comment]
Hey, no biggie, didn't mean to sound negative, just wanted to point out the
reality of the situation. I do hope you get some more time though :)

**Comment by FKLC** [comment]
Please check if the latest version works. Not sure what causes this, but updated baileys (the whatsapp library), so might be working now.

**Comment by FKLC** [comment]
Closing the issue due to inactivity.
