### ISSUE TITLE
I didn't get the QR image to scan!

### ISSUE THREAD

**Issue by hm43** [FKLC/WhatsAppToDiscord#131]
I followed the steps from this guide https://fklc.github.io/WhatsAppToDiscord/#/setup
the #control-room channel was created but I can't see the QR image
NB: I'm on Mac so I did run WA2DC-macOS

**Comment by FKLC** [comment]
Looking at your logs, I don't really understand what might be causing this issue. I changed node version from 16 to 18, so it might be the reason, but not I'm sure. I'll try to push some updates today, and I'll change node back to 16, see if that'll work.

**Comment by FKLC** [comment]
Okay, I found the reason and working on it.

**Comment by FKLC** [comment]
following in #134
