### ISSUE TITLE
Crashes when audio is received or sent

### ISSUE THREAD

**Issue by S0FLGotTaken** [FKLC/WhatsAppToDiscord#132]
Whenever I receive or send an audio in whatsapp, the .exe crashes.

**Comment by FKLC** [comment]
Could you send your logs?

**Comment by S0FLGotTaken** [comment]
> Could you send your logs?
Where are those?

**Comment by FKLC** [comment]
It is in the same folder as your bot. Check the folder you run the executable from and you'll find logs.txt file.

**Comment by S0FLGotTaken** [comment]
I'm not really comfortable with sharing my phone number. Is there anything specific you want from logs?

**Comment by FKLC** [comment]
Yeah, can you crash the bot purposefully then find a line similar to the following `{"level":30,"time":1679515369266,"pid":10012,"hostname":"","version":"v0.10.0","msg":"Exiting!"}`, then send the line showing the error, it should look similar to `{"level":50,"time":1679515369266,"pid":10012,"hostname":"redacted","":"v0.9.1","err":{"type":"TypeError","message":"Cannot read properties of undefined (reading 'channels')","stack":"TypeError: Cannot read properties of undefined (reading 'channels')\n    at Object.repairChannels (path\\WhatsAppToDiscord\\src\\utils.js:209:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async path\\WhatsAppToDiscord\\src\\index.js:41:3"},"msg":"Cannot read properties of undefined (reading 'channels')"}`

**Comment by S0FLGotTaken** [comment]
So um the log has 2400 lines and many many instances of the word "error" and "Exiting!"

**Comment by S0FLGotTaken** [comment]
This was the last error recorded:
{"level":30,"time":1679534650053,"pid":3292,"hostname":"S0FL_LAP","version":"v0.9.1","msgAttrs":{"from":"120363022180714450@g.us","type":"text","id":"1C687B6422740C6BE249CA018F19C86B","participant":"----@s.whatsapp.net","offline":"0","addressing_mode":"pn","notify":"Vanzela💕","t":"1679533415"},"retryCount":1,"msg":"sent retry receipt"}
{"level":30,"time":1679534650316,"pid":3292,"hostname":"S0FL_LAP","version":"v0.9.1","msgAttrs":{"from":"120363022180714450@g.us","type":"text","id":"93F6817C66236A19079FD199E1261CC0","participant":"----@s.whatsapp.net","offline":"0","addressing_mode":"pn","notify":"Vanzela💕","t":"1679533417"},"retryCount":1,"msg":"sent retry receipt"}
{"level":30,"time":1679534650579,"pid":3292,"hostname":"S0FL_LAP","version":"v0.9.1","msgAttrs":{"from":"120363022180714450@g.us","type":"text","id":"88AB347192CE29318081AEA885BF1352","participant":"----@s.whatsapp.net","offline":"0","addressing_mode":"pn","notify":"Vanzela💕","t":"1679533425"},"retryCount":1,"msg":"sent retry receipt"}
{"level":30,"time":1679534650841,"pid":3292,"hostname":"S0FL_LAP","version":"v0.9.1","msgAttrs":{"from":"120363022180714450@g.us","type":"text","id":"58FB312B8FAB392DBBD7607CFBB7A290","participant":"----@s.whatsapp.net","offline":"0","addressing_mode":"pn","notify":"Vanzela💕","t":"1679533436"},"retryCount":1,"msg":"sent retry receipt"}
{"level":30,"time":1679534651104,"pid":3292,"hostname":"S0FL_LAP","version":"v0.9.1","msgAttrs":{"from":"120363022180714450@g.us","type":"text","id":"3A3D6DFC39A6DD4F72FBF928E089FB4D","participant":"----@s.whatsapp.net","offline":"0","addressing_mode":"pn","notify":"Vanzela💕","t":"1679533439"},"retryCount":1,"msg":"sent retry receipt"}
{"level":30,"time":1679534651365,"pid":3292,"hostname":"S0FL_LAP","version":"v0.9.1","msgAttrs":{"from":"120363022180714450@g.us","type":"text","id":"0F79D1F76661CE1A778714C668E6A590","participant":"----@s.whatsapp.net","offline":"0","addressing_mode":"pn","notify":"Vanzela💕","t":"1679533444"},"retryCount":1,"msg":"sent retry receipt"}
{"level":30,"time":1679534651627,"pid":3292,"hostname":"S0FL_LAP","version":"v0.9.1","msgAttrs":{"from":"120363022180714450@g.us","type":"text","id":"4892BF8672019192E1EA5BDC90BFF04C","participant":"----@s.whatsapp.net","offline":"0","addressing_mode":"pn","notify":"Vanzela💕","t":"1679533450"},"retryCount":1,"msg":"sent retry receipt"}
{"level":30,"time":1679534651889,"pid":3292,"hostname":"S0FL_LAP","version":"v0.9.1","msgAttrs":{"from":"120363022180714450@g.us","type":"text","id":"8CEBFF4CBEF70E1FDBB250DBD631916D","participant":"----@s.whatsapp.net","offline":"0","addressing_mode":"pn","notify":"Vanzela💕","t":"1679533484"},"retryCount":1,"msg":"sent retry receipt"}
{"level":30,"time":1679534652153,"pid":3292,"hostname":"S0FL_LAP","version":"v0.9.1","msgAttrs":{"from":"120363022180714450@g.us","type":"text","id":"8146CDC73E02603A9C85D8E1187700FA","participant":"----@s.whatsapp.net","offline":"0","addressing_mode":"pn","notify":"Vanzela💕","t":"1679533523"},"retryCount":1,"msg":"sent retry receipt"}
{"level":50,"time":1679534670354,"pid":3292,"hostname":"S0FL_LAP","version":"v0.9.1","err":{"type":"TypeError","message":"Invalid host defined options","stack":"TypeError: Invalid host defined options\n    at C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:942:53\n    at C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\util\\dist\\index.js:35:33\n    at RequestManager.resolveRequest (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:1111:48)\n    at RequestManager.queueRequest (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:1056:46)\n    at REST.raw (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:1330:32)\n    at REST.request (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:1321:33)\n    at REST.post (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:1283:17)\n    at Webhook.send (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\discord.js\\src\\structures\\Webhook.js:222:38)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Client.<anonymous> (C:\\snapshot\\WhatsAppToDiscord\\src\\discordHandler.js:63:24)"},"msg":"Invalid host defined options"}
{"level":30,"time":1679534670354,"pid":3292,"hostname":"S0FL_LAP","version":"v0.9.1","msg":"Exiting!"}

**Comment by FKLC** [comment]
Okay, I just deleted your comment because it still phone numbers in it, but honestly, I don't know the reason for this problem. Did you check if you are still having the same problem with the latest release? I saw that you were using version 9.0.1, I recently pushed a new version, see if that works.

**Comment by S0FLGotTaken** [comment]
If you're talking about the 1-0-6-0-2-8-7-4-5-@g.u phone number, that's not related to me at all and idk what it is or what it's for, but thank you.

Also, updated and here's the log, hopefully with no more numbers:
{"level":30,"time":1679540201025,"pid":7620,"hostname":"LAPTOP-H1Q4CBVF","version":"v0.10.0","msg":"Starting"}
{"level":30,"time":1679540201381,"pid":7620,"hostname":"LAPTOP-H1Q4CBVF","version":"v0.10.0","msg":"Update checked."}
{"level":30,"time":1679540201542,"pid":7620,"hostname":"LAPTOP-H1Q4CBVF","version":"v0.10.0","msg":"Synced table."}
{"level":30,"time":1679540201543,"pid":7620,"hostname":"LAPTOP-H1Q4CBVF","version":"v0.10.0","msg":"Loaded settings."}
{"level":30,"time":1679540201545,"pid":7620,"hostname":"LAPTOP-H1Q4CBVF","version":"v0.10.0","msg":"Loaded contacts."}
{"level":30,"time":1679540201546,"pid":7620,"hostname":"LAPTOP-H1Q4CBVF","version":"v0.10.0","msg":"Loaded chats."}
{"level":30,"time":1679540202285,"pid":7620,"hostname":"LAPTOP-H1Q4CBVF","version":"v0.10.0","msg":"Discord client started."}
{"level":30,"time":1679540203069,"pid":7620,"hostname":"LAPTOP-H1Q4CBVF","version":"v0.10.0","msg":"Repaired channels."}
{"level":30,"time":1679540203184,"pid":7620,"hostname":"LAPTOP-H1Q4CBVF","version":"v0.10.0","msg":"WhatsApp client started."}
{"level":30,"time":1679540203686,"pid":7620,"hostname":"LAPTOP-H1Q4CBVF","version":"v0.10.0","browser":["WA2DC","Chrome","4.0.0"],"helloMsg":{"clientHello":{"ephemeral":"DVkV824EQAm5qPKhyvpbWCcVImz1P+HjQYzCSL5ojn8="}},"msg":"connected to WA Web"}
{"level":30,"time":1679540203854,"pid":7620,"hostname":"LAPTOP-H1Q4CBVF","version":"v0.10.0","node":{"username":"MY_PHONE_NUMBER","passive":true,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2308,"tertiary":7},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","device":13},"msg":"logging in..."}
{"level":30,"time":1679540204227,"pid":7620,"hostname":"LAPTOP-H1Q4CBVF","version":"v0.10.0","msg":"30 pre-keys found on server"}
{"level":30,"time":1679540204388,"pid":7620,"hostname":"LAPTOP-H1Q4CBVF","version":"v0.10.0","msg":"opened connection to WA"}
{"level":30,"time":1679540204505,"pid":7620,"hostname":"LAPTOP-H1Q4CBVF","version":"v0.10.0","msg":"handled 33 offline messages/notifications"}
{"level":30,"time":1679540204732,"pid":7620,"hostname":"LAPTOP-H1Q4CBVF","version":"v0.10.0","jid":"SOMEONES_PHONE_NUMBER@s.whatsapp.net","msg":"identity changed"}
{"level":50,"time":1679540210346,"pid":7620,"hostname":"LAPTOP-H1Q4CBVF","version":"v0.10.0","err":{"type":"TypeError","message":"Invalid host defined options","stack":"TypeError: Invalid host defined options\n    at C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:942:53\n    at C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\util\\dist\\index.js:35:33\n    at RequestManager.resolveRequest (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:1111:48)\n    at RequestManager.queueRequest (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:1056:46)\n    at REST.raw (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:1330:32)\n    at REST.request (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:1321:33)\n    at REST.post (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:1283:17)\n    at Webhook.send (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\discord.js\\src\\structures\\Webhook.js:222:38)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Client.<anonymous> (C:\\snapshot\\WhatsAppToDiscord\\src\\discordHandler.js:66:24)"},"msg":"Invalid host defined options"}
{"level":30,"time":1679540210346,"pid":7620,"hostname":"LAPTOP-H1Q4CBVF","version":"v0.10.0","msg":"Exiting!"}

**Comment by FKLC** [comment]
following in #134
