### ISSUE TITLE
View once messages crashing

### ISSUE THREAD

**Issue by S0FLGotTaken** [FKLC/WhatsAppToDiscord#133]
Sent by myself on whatsapp, image and video crashes.

`{"level":30,"time":1679540803024,"pid":1808,"hostname":"PC_NAME","version":"v0.10.0","msg":"Starting"}
{"level":30,"time":1679540803388,"pid":1808,"hostname":"PC_NAME","version":"v0.10.0","msg":"Update checked."}
{"level":30,"time":1679540803538,"pid":1808,"hostname":"PC_NAME","version":"v0.10.0","msg":"Synced table."}
{"level":30,"time":1679540803540,"pid":1808,"hostname":"PC_NAME","version":"v0.10.0","msg":"Loaded settings."}
{"level":30,"time":1679540803541,"pid":1808,"hostname":"PC_NAME","version":"v0.10.0","msg":"Loaded contacts."}
{"level":30,"time":1679540803543,"pid":1808,"hostname":"PC_NAME","version":"v0.10.0","msg":"Loaded chats."}
{"level":30,"time":1679540804199,"pid":1808,"hostname":"PC_NAME","version":"v0.10.0","msg":"Discord client started."}
{"level":30,"time":1679540804999,"pid":1808,"hostname":"PC_NAME","version":"v0.10.0","msg":"Repaired channels."}
{"level":30,"time":1679540805087,"pid":1808,"hostname":"PC_NAME","version":"v0.10.0","msg":"WhatsApp client started."}
{"level":30,"time":1679540805302,"pid":1808,"hostname":"PC_NAME","version":"v0.10.0","browser":["WA2DC","Chrome","4.0.0"],"helloMsg":{"clientHello":{"ephemeral":"might_just_be_sensitive_info="}},"msg":"connected to WA Web"}
{"level":30,"time":1679540805465,"pid":1808,"hostname":"PC_NAME","version":"v0.10.0","node":{"username":"MY_NUMBER","passive":true,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2308,"tertiary":7},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","device":13},"msg":"logging in..."}
{"level":30,"time":1679540805834,"pid":1808,"hostname":"PC_NAME","version":"v0.10.0","msg":"30 pre-keys found on server"}
{"level":30,"time":1679540805993,"pid":1808,"hostname":"PC_NAME","version":"v0.10.0","msg":"opened connection to WA"}
{"level":30,"time":1679540806054,"pid":1808,"hostname":"PC_NAME","version":"v0.10.0","msg":"handled 3 offline messages/notifications"}
{"level":50,"time":1679540829191,"pid":1808,"hostname":"PC_NAME","version":"v0.10.0","err":{"type":"TypeError","message":"Invalid host defined options","stack":"TypeError: Invalid host defined options\n    at C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:942:53\n    at C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\util\\dist\\index.js:35:33\n    at RequestManager.resolveRequest (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:1111:48)\n    at RequestManager.queueRequest (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:1056:46)\n    at REST.raw (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:1330:32)\n    at REST.request (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:1321:33)\n    at REST.post (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@discordjs\\rest\\dist\\index.js:1283:17)\n    at Webhook.send (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\discord.js\\src\\structures\\Webhook.js:222:38)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Client.<anonymous> (C:\\snapshot\\WhatsAppToDiscord\\src\\discordHandler.js:66:24)"},"msg":"Invalid host defined options"}
{"level":30,"time":1679540829191,"pid":1808,"hostname":"PC_NAME","version":"v0.10.0","msg":"Exiting!"}`

**Comment by FKLC** [comment]
following on #134
