### ISSUE TITLE
Doesn't show the qr code

### ISSUE THREAD

**Issue by Nerodacles** [FKLC/WhatsAppToDiscord#135]
**Describe the bug**
It just dosent creates the qr code in the `control-room` channel, and just starts reconnecting to whatsapp, i just did a new first run of the bot.

**To Reproduce**
1. Just do a first run of the bot.

**Expected behavior**
That the bot sends the qr code to the `control-room` channel.

**Logs**
![image](https://user-images.githubusercontent.com/29661633/227234379-2f8a13ab-18cb-4c64-a9bb-aeb2fef606f6.png)
![image](https://user-images.githubusercontent.com/29661633/227234505-33290045-952e-47cb-91a2-c320106f47bb.png)
[logs.txt](https://github.com/FKLC/WhatsAppToDiscord/files/11052026/logs.txt)

**Platform**
 - OS: Windows

**Comment by FKLC** [comment]
Are you able to use whatsapp web on the same computer HOMESVR? Not sure what might be reason, but your logs indicate your bot fails to connect whatsapp's websocket. so, I'm not sure what might be the reason. Check if you can use whatsapp web normally on the same computer. if you can use it, but you can't use the bot, then I don't really know what might be causing this.

**Comment by Nerodacles** [comment]
> Are you able to use whatsapp web on the same computer HOMESVR? Not sure what might be reason, but your logs indicate your bot fails to connect whatsapp's websocket. so, I'm not sure what might be the reason. Check if you can use whatsapp web normally on the same computer. if you can use it, but you can't use the bot, then I don't really know what might be causing this.

Yea.

![image](https://user-images.githubusercontent.com/29661633/227242579-a04600e4-a2ff-49ba-9b2d-11fe14e63aa7.png)

**Comment by Nerodacles** [comment]
i did log in, and it works just fine...

**Comment by Nerodacles** [comment]
Do you know where it does store the baileys store? it isn't on %appdata%

**Comment by Nerodacles** [comment]
It was the windows on that machine...

**Comment by TukangM** [comment]
try change the dns

**Comment by Nerodacles** [comment]
> try change the dns

It didn't work at all.

**Comment by TukangM** [comment]
try remove storage.db. its contain login indo and token

**Comment by Nerodacles** [comment]
> try remove storage.db. its contain login indo and token

Bro, i did it on a fresh install.... it didn't have the storage.db

But thanks for your help!
