### ISSUE TITLE
discord chat to whatsapp not working if #groupx moved into other category

### ISSUE THREAD

**Issue by TukangM** [FKLC/WhatsAppToDiscord#136]
**Describe the bug**
a whatsapp group discord to whatsapp chat dosent sent to group because at the discord when i move the #group-category to up / other catogory 

**To Reproduce**
1. first summon the group whatsapp
![image](https://user-images.githubusercontent.com/91467886/227705248-5e747d18-e74e-4b52-9600-7d50a41e5e3d.png) > ![image](https://user-images.githubusercontent.com/91467886/227705239-5e849279-3e5f-4925-852f-c88a80fd2e51.png)
2.move the #groupx into other category 
![image](https://user-images.githubusercontent.com/91467886/227705317-91653353-cdf5-48bb-877d-4754a3cab800.png)
3.try chat on whatsapp and discord
![image](https://user-images.githubusercontent.com/91467886/227705347-0649d977-2ec0-4580-a29f-e41f619fbce2.png)
discord to whatsapp chat not working if the #group moved into other category

**Platform**
 - OS: Windows 10 22H2, Ubuntu 22.04 WSL

**Comment by TukangM** [comment]
![image](https://user-images.githubusercontent.com/91467886/227705449-d79557dd-4750-46ce-8359-948e62ee4709.png)
if i move #groupx into whatsapp category. discord-->  sycn <-- whatsapp  are working

**Comment by FKLC** [comment]
Was this working with the old versions?

**Comment by FKLC** [comment]
Nevermind, tested it myself. Fixing it now.

**Comment by FKLC** [comment]
new version should fix it. i'll release it in a minute
