### ISSUE TITLE
Bot crashing

### ISSUE THREAD

**Issue by arespawn** [FKLC/WhatsAppToDiscord#137]
**Describe the bug**
The bot crashes on Ubuntu 20.04.4 LTS after 1 or 2 messages, I suspect it has to do when its chatting with whatsapp groups as trying 1on1 chat seems to be okay although it stills throws a mutex deadlock but it doesn't crash the bot yet.

**To Reproduce**
1. start sending messages through the bot
2. it shows some mutex deadlock error and it crashes/quits
3. See the error

**Expected behavior**
Should not be crashing

**Logs**
[logs.txt](https://github.com/FKLC/WhatsAppToDiscord/files/11292155/logs.txt)
**Platform**
Ubuntu 20.04.4 LTS

**Additional context**
[terminal output.odt](https://github.com/FKLC/WhatsAppToDiscord/files/11292170/terminal.output.odt)

**Comment by JasperTheMinecraftDev** [comment]
That's because your internet disconnects, it's not due to the mutex deadlock errors. When your internet is gone it just quits the program instead of trying again.

**Comment by arespawn** [comment]
Oh i see! Then we can change to an enchantment for the future thank you for the answer.

On 9 Jun 2023, at 10:21, JasperTheMinecraftDev ***@***.***> wrote:

﻿

That's because your internet disconnects, it's not due to the mutex deadlock errors. When your internet is gone it just quits the program instead of trying again.

**Comment by FKLC** [comment]
Fixed this bug. It was because you received a weird emoji to your message and it crashed.
