### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ishannaik** [FKLC/WhatsAppToDiscord#138]
How do I make it so that only messages from one group sync and not everything else,
I only want to sync my college whatsapp group to discord to sync all the important messages and announcements is there anyway to do that? Also how do I make sure that my personal chats wont get leaked and only the group messages will be sent

**Comment by TukangM** [comment]
![image](https://user-images.githubusercontent.com/91467886/234750202-4f34eb97-6239-4cce-865c-4a42c30d4769.png)

[addToWhitelist](https://fklc.github.io/WhatsAppToDiscord/#/commands?id=addtowhitelist)
Adds the given channel to the whitelist.

Format: addToWhitelist #<channel name>
Examples:
addToWhitelist #john-doe: This would add John Doe to the whitelist, allowing them to send you a message if you have whitelist enabled.

**Comment by TukangM** [comment]
just add addToWhitelist #College_name_group_of_discord_text_channel

![image](https://user-images.githubusercontent.com/91467886/234750423-e8fbbeb8-e0e6-45bb-a970-88e4da8a1bb8.png)

**Comment by hamma741** [comment]
this link it helps you 
https://startadam.com/connect-whatsapp-discord/

**Comment by TukangM** [comment]
> this link it helps you https://startadam.com/connect-whatsapp-discord/

No. its paid. the product is focused on business

**Comment by FKLC** [comment]
Closing the issue due to inactivity.
