### ISSUE TITLE
How to generate a new QR Code?

### ISSUE THREAD

**Issue by aspache** [FKLC/WhatsAppToDiscord#139]
Hello,

I have to regenerate the QR Code because I have desconnected from whatsapp, but when I try to read the old QR Code I receive a message saying its failed.

Is there any command that i can generate a new one?

Thanks!
![Screenshot_2](https://github.com/FKLC/WhatsAppToDiscord/assets/52223516/59333030-9eae-4032-b8d3-acd9006a3075)

**Comment by spookycookie27** [comment]
yeah same issue has been around for a while.

So far the only fix is to delete everything and start again, 
Kick Bot, go to discord dev site, delete pp,  create new App create new BOT

**Comment by FKLC** [comment]
Are you able to see if the latest version is working?
