### ISSUE TITLE
Make it a tray application

### ISSUE THREAD

**Issue by IOplus** [FKLC/WhatsAppToDiscord#140]
**Is your feature request related to a problem? Please describe.**
It's not a problem, it just annoys me a bit to have a terminal window opened all the time...

**Describe the solution you'd like**
Make it a tray application. Display the terminal window only on first run and when the setup is completed close it and minimize to tray.

**Describe alternatives you've considered**
An option in settings to not show the window and make it run as a background service, and then we would need a command to stop the bot from the control-room chat.

**Comment by HClausing** [comment]
I did something similar creating a start.bat file on the WA2DC root folder, running the WA2CD.exe, then, added it to Scheduled Tasks on Windows, running when computer starts (even without any user logged).

**Comment by FKLC** [comment]
While this is a good idea, with the current compilation methods, it is pretty hard to hide the console. Even if I did, then I would have to come up with a way to create a tray icon, and this would only be for windows. So yeah, while I agree that it would be a great enhancement, it adds unreasonable complexity. So, unfortunately, I won't be implementing this, sorry.
