### ISSUE TITLE
Connection Failure

### ISSUE THREAD

**Issue by stnKrisna** [FKLC/WhatsAppToDiscord#142]
**Describe the bug**
Authentication to whatsapp always fails.

**To Reproduce**
1. Use the bot

**Expected behavior**
Auth should work.

**Logs**
If needed add your logs.txt after redacting any private information.

**Platform**
 - Any

**Additional context**
Original package now deprecated. Repo has been taken down: https://www.npmjs.com/package/@adiwajshing/baileys
Use new package instead: https://github.com/WhiskeySockets/Baileys

According to the new repo (https://github.com/WhiskeySockets/Baileys#connecting-multi-device-recommended)
> This is done as WA seems to have completely dropped support for the legacy version.

For those who needs a quick fix, you can download the latest release and replace the baileys package under `node_modules/@adiwajshing` with the content of the release archive they provided. It looks like its backwards compatible with the one this project uses.

**Comment by FKLC** [comment]
Please check if the latest version is working.
