### ISSUE TITLE
Linux version isn't working.

### ISSUE THREAD

**Issue by JasperTheMinecraftDev** [FKLC/WhatsAppToDiscord#143]
**Describe the bug**

**To Reproduce**
1. Follow the setup
2. Scan the QR
3. See the bot retrying but never succeeding.

**Expected behavior**

**Logs**
If needed add your logs.txt after redacting any private information.

**Platform**
 - OS: [e.g. Windows, MacOS, Linux]

**Additional context**

**Comment by jonzinho** [comment]
I have the same bug as you on Linux version too.

**Comment by FKLC** [comment]
Please check if the latest version is working.

**Comment by JasperTheMinecraftDev** [comment]
Will do!
Van: Fatih Victor ***@***.***>
Verzonden: zaterdag 10 juni 2023 22:32
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [FKLC/WhatsAppToDiscord] Linux version isn't working. (Issue #143)


Please check if the latest version is working.

**Comment by JasperTheMinecraftDev** [comment]
I can happily confirm that it's working on linux now. Thanks for the quick fix!
