### ISSUE TITLE
Channels not saving anymore.

### ISSUE THREAD

**Issue by JasperTheMinecraftDev** [FKLC/WhatsAppToDiscord#146]
Hey, previously(when I ran it on windows and not with the latest version) channels were saved so they could continue when the bot restarts. This is not the case anymore with the new and linux version, my channels are unlinked when I restart the bot(I can't do CTRL + C as I use pterodactyl, just killing the bot, probably that's it).

Also, where are they saved? In the chats file? Wanting to modify the discord channel ID's.

**Comment by FKLC** [comment]
Channels are autosaved every 5 minutes. So it is possible that you lost chats that were opened in the last 5 minutes before killing the bot. I'll keep 5 minutes, but make it configurable, so that you can have more frequent autosaves.

**Comment by JasperTheMinecraftDev** [comment]
Sounds good. Thanks for the clarification!

**Comment by JasperTheMinecraftDev** [comment]
Kinda forgot it but where are they stored?

**Comment by FKLC** [comment]
Oh sorry, yeah, they are stored in storage/chats file. it is a JSON file.

**Comment by JasperTheMinecraftDev** [comment]
Alright, thank you!
