### ISSUE TITLE
Bot going offline immediately once added, and not posting QR code in command center chat

### ISSUE THREAD

**Issue by User3000000** [FKLC/WhatsAppToDiscord#152]
**Describe the bug**
Bot going offline immediately once added, and not posting QR code in command center chat

**To Reproduce**
1. Set up bot as normal
2. when accepted into server, bot creates a channel but doesn't post QR code
3. See error

**Expected behavior**
Bot going offline immediately once added, and not posting QR code in command center chat

**Logs**
If needed add your logs.txt after redacting any private information.

**Platform**
 - OS: Windows

**Additional context**
First time setting up

**Comment by INVIS1BLE3000** [comment]
Same prob

**Comment by FKLC** [comment]
Unfortunately I couldn't reproduce this bug. You have to upload your logs and I'll check if there's anything that can be done about it, but otherwise there's nothing much I can do.

**Comment by INVIS1BLE3000** [comment]
> Unfortunately I couldn't reproduce this bug. You have to upload your logs and I'll check if there's anything that can be done about it, but otherwise there's nothing much I can do.
[logs.txt](https://github.com/FKLC/WhatsAppToDiscord/files/11970379/logs.txt)

**Comment by FKLC** [comment]
This is happening because the bot doesn't have message intent. See step 8 at the [setup docs](https://fklc.github.io/WhatsAppToDiscord/#/setup). After enabling the message intent, you need to kick and invite the bot back again, and to do so, you first have to delete the storage folder and go through the invitation process again.

**Comment by FKLC** [comment]
Closing the issue due to inactivity.
