### ISSUE TITLE
How do discord/whatsapp group chats work?

### ISSUE THREAD

**Issue by AngelDustArt** [FKLC/WhatsAppToDiscord#153]
While experimenting with the bot, I wondered if it's possible for members who chat on Discord to appear directly with their profiles on WhatsApp in a group chat. Instead of all the messages appearing as if I sent them, is there a way to make them appear separately and more cleanly, as if they were writing from their own profiles, of course?

**Comment by FKLC** [comment]
Yes it is possible. See [enableDCPrefix](https://fklc.github.io/WhatsAppToDiscord/#/commands?id=enabledcprefix) command.

**Comment by FKLC** [comment]
unfortunately it isn't possible. because unlike discord, you can't specify a profile picture for each message in WhatsApp.

**Comment by PabloFraustro** [comment]
Hello @FKLC, thank you very much for your contributions! Following @AngelDustArt comment ... Is there no way then to receive messages in WhatsApp from Discord with different phone numbers? (Link Discord's profile with user's phone number)

**Comment by FKLC** [comment]
the closest possible say is to using webhooks and the bot already uses them. theres no other way unfortunately.

**Comment by FKLC** [comment]
Closing this issue as it is impossible to implement.
