### ISSUE TITLE
Bot crashes and goes offline when receiving audio call.

### ISSUE THREAD

**Issue by mastanoob** [FKLC/WhatsAppToDiscord#155]
**Describe the bug**
WhatsApp bot abruptly crashes and goes offline when receiving a voice call via WhatsApp. The Discord server shows the channel with name of the person who is calling but the channel it self is empty of any content.  

**To Reproduce**
1. start the bot as per the instructions
2. receive a voice call via WhatsApp
3. channel opens up with the name of the person calling 

**Expected behavior**
The bot should not crash and go offline. It should be able to at least let the call ring and continue on with its functionalities. 

**Logs**
[logs.txt](https://github.com/FKLC/WhatsAppToDiscord/files/12276255/logs.txt)

**Platform**
 - OS: [Ubuntu 18.04.6 LTS]

**Additional context**
Initially this occurred with server running with 30-40+ channels but kept crashing so we did a fresh install plus new server to replicate the issue; It's still persistent. Also tried with the Windows version, it's still persistent. See attached log.txt file

**Comment by mastanoob** [comment]
right now the server is running using: `while true; do node .; sleep 2; done;`. It restarts the server and the channels which were from previous iteration get removed from "WHATSAPP" channel group header and placed outside.

**Comment by f-wllr** [comment]
I have the same problem. OS of bot host is Windows 10 Home
