### ISSUE TITLE
Possibility of one to one chat content between Whatsapp on phone and Discord server

### ISSUE THREAD

**Issue by mastanoob** [FKLC/WhatsAppToDiscord#156]
- Its counter intuitive that chats on Whatapp App and the ones on Discord server are not of same time-stamp/ period. 

- There should be a command which can be executed from control-room to sync between Whatsapp and Discord server.

**Comment by mastanoob** [comment]
nvm, I think Baileys doesn't support this functionality.

**Comment by FKLC** [comment]
You can technically load some old messages, but it is very limited and would require deleting and resending already sent messages. So, while possible, it would be hard to implement and add a lot more complexity.
