### ISSUE TITLE
tweak nr 2

### ISSUE THREAD

**Issue by DAMmcpe** [FKLC/WhatsAppToDiscord#16]
Please make it, so that 1st, nicknames can be also displayed(I got blamed bc in the whatsapp group was the message [SmallPP] thx)

And an other thing, bc im using my main whatsapp account for the bridge, my message dont appear, maybe you could tweak it a bit, so that there is  a setting, that only when a message with "[" starts, it will be send! That way, my message will appear, and there will be NO infinty loop

**Comment by FKLC** [comment]
I couldn't reproduce the bug about infinity loop but changed the username thing. I published under the same version but you need to download again.

**Comment by DAMmcpe** [comment]
So now if I write a msg in the whatsapp group it will also appear in the discord?

**Comment by FKLC** [comment]
Oh, I didn't get what you meant in the first time but the latest release should work.

**Comment by DAMcraft** [comment]
if I send piictures myslef they wont appear too

**Comment by FKLC** [comment]
Updated once more. Latest release should work.
