### ISSUE TITLE
After a days running the bot lost connection, how to regenerate a qrcode?

### ISSUE THREAD

**Issue by lokize** [FKLC/WhatsAppToDiscord#164]
First, thanks for WhatsAppToDiscord its a amazing project.

After a days running the bot lost connection, how to generate a new qrcode without losing all chats and data?

![image](https://github.com/FKLC/WhatsAppToDiscord/assets/19701630/86f94077-6239-43c9-9de6-769cd0450240)

**Comment by FKLC** [comment]
I don't know what is causing this issue, but as a quick solution you can delete baileys folder inside the storage folder. That should force the bot to regenerate a qr code. Close the bot, delete the folder, rerun the bot. Should be fine.

**Comment by lokize** [comment]
Thanks, the solution worked.

How to see a log of my problem to prevent it from happening again?

**Comment by FKLC** [comment]
You should be able to read logs from logs.txt, but I'm not sure if there will be anything useful. This seems like a logic issue, rather than an exception, and unfortunately I can't think of a way to reproduce it.
