### ISSUE TITLE
Feature Requests, Channel Rename command, Chat history restore

### ISSUE THREAD

**Issue by Ishannaik** [FKLC/WhatsAppToDiscord#174]
Feature Request 1: Channel Rename Command

Is your feature request related to a problem? Please describe.
I often encounter a situation where random numbers appear instead of contact names for the person or for the group, making it necessary to manually readd them using start command by deleting them for identification.

Describe the solution you'd like
I suggest implementing an "add a rename command" feature in WA2DC's GitHub repository. This command would allow users to rename channels, addressing the issue of displaying random numbers/contact number instead of contact names.

Describe alternatives you've considered
As an alternative, users could manually rename channels, but this causes the bot to disconnect from the channel.

Feature Request 2: Chat History Restore Command

Is your feature request related to a problem? Please describe.
Sometimes, channels get deleted during server switching/switching hosting services, creating difficulty in retrieving chat history. To address this, I propose adding a "restorechathistory [number of messages]" command to WA2DC.

Describe the solution you'd like
I suggest implementing a command that allows users to restore chat history in case of channel deletion and I want to recreate the dm with history. The command should be able to pull the for eg last 100 messages from DMs or save the entire chat history on DC.

Feature Request 3: Updating documentation to be more detailed

I am having trouble understand what these commands do
LastMessageStorage
publishing messages? What are they

**Comment by Kp4103** [comment]
Would be great to have this feature, it is a bit troublesome when numbers appear instead of contact saved names

**Comment by FKLC** [comment]
I will look into feature request 1 and 3, but not to 2 because it requires a lot of changes/effort. Also as a quick note, you should be able to manually rename channels. I tried manually editing the channel name and it works, and considering the way the bot works, name of the channels shouldn't affect the way the bot operates.

**Comment by FKLC** [comment]
Resync command now automatically renames channels.
