### ISSUE TITLE
Disable update prompt when starting bot

### ISSUE THREAD

**Issue by febeus** [FKLC/WhatsAppToDiscord#178]
**Is your feature request related to a problem? Please describe.**
On Ubuntu, bot sometime hang or auto end. So scheduled a daily reboot/service restart. It was pause again on update prompt which require human interaction.

**Describe the solution you'd like**
A perimeter to bypass update check or auto accept update.

**Describe alternatives you've considered**
any

**Additional context**
na

**Comment by lokize** [comment]
+1 for this, every update my container stopped and its necessary recompile and create a new container with new agent :(

**Comment by FKLC** [comment]
See the latest update. Thank you for the suggestion!

**Comment by FKLC** [comment]
> +1 for this, every update my container stopped and its necessary recompile and create a new container with new agent :(

I started building the docker images myself but it is basically node + the repo. So, it's size is larger than binary version. However, if you prefer not having to build it yourself you can use it. https://hub.docker.com/r/fklc/wa2dc

**Comment by aasalmeida** [comment]
Hi
How can I disable the auto-update or auto-update prompt at app startup?
So, does the .exe supports parameters, like: /no-update, --noupdate or something like this?
