### ISSUE TITLE
WA2DC Window Closed

### ISSUE THREAD

**Issue by Kavallerist** [FKLC/WhatsAppToDiscord#18]
When the WA2DC window it's closed the bot stops working. Still the bot works fantastic.

**Comment by FKLC** [comment]
Yes, this is an expected behaviour. It is impossible to run bot without a process. You might run it on a server that run 7/24 but that would be (IMO) useless. If that was the only reason for opening this issue please feel free to close it.

**Comment by Kavallerist** [comment]
Thank you for the response
