### ISSUE TITLE
Crash when starting a new conversation

### ISSUE THREAD

**Issue by Corrosivex** [FKLC/WhatsAppToDiscord#186]
**Describe the bug**

When I try to open a conversation it automatically creates the channel and crash.

**To Reproduce**

1. Open XA2DC.exe
2. start <anycontact>
3. Crash

**Logs**
`{"level":30,"time":1710441488760,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","msg":"Starting"}
{"level":30,"time":1710441489175,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","msg":"Update checked."}
{"level":30,"time":1710441489175,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","msg":"Conversion completed."}
{"level":30,"time":1710441489177,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","msg":"Loaded settings."}
{"level":30,"time":1710441489177,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","msg":"Changed auto save interval."}
{"level":30,"time":1710441489177,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","msg":"Loaded contacts."}
{"level":30,"time":1710441489177,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","msg":"Loaded chats."}
{"level":30,"time":1710441489178,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","msg":"Loaded last messages."}
{"level":30,"time":1710441489970,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","msg":"Discord client started."}
{"level":30,"time":1710441490587,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","msg":"Repaired channels."}
{"level":30,"time":1710441490711,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","msg":"WhatsApp client started."}
{"level":30,"time":1710441490868,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","browser":["Firefox (Linux)","",""],"helloMsg":{"clientHello":{"ephemeral":"Sc5nuGXNAHaPoczMWpYXwdkogWtGYaWg6S0SjZGgh0A="}},"msg":"connected to WA"}
{"level":30,"time":1710441490937,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","node":{"username":"34616247663","passive":true,"userAgent":{"platform":"MACOS","appVersion":{"primary":2,"secondary":2403,"tertiary":2},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","device":21},"msg":"logging in..."}
{"level":30,"time":1710441491402,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","msg":"27 pre-keys found on server"}
{"level":30,"time":1710441491467,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","msg":"opened connection to WA"}
{"level":30,"time":1710441491588,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","msg":"handled 0 offline messages/notifications"}
{"level":50,"time":1710441500070,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","err":{"type":"DiscordAPIError","message":"Missing Permissions","stack":"DiscordAPIError: Missing Permissions\n    at RequestHandler.execute (C:\\snapshot\\WhatsAppToDiscord\\out.js)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async RequestHandler.push (C:\\snapshot\\WhatsAppToDiscord\\out.js)\n    at async GuildChannelManager.createWebhook (C:\\snapshot\\WhatsAppToDiscord\\out.js)\n    at async Object.getOrCreateChannel (C:\\snapshot\\WhatsAppToDiscord\\out.js)\n    at async start (C:\\snapshot\\WhatsAppToDiscord\\out.js)\n    at async Client.<anonymous> (C:\\snapshot\\WhatsAppToDiscord\\out.js)","name":"DiscordAPIError","method":"post","path":"/channels/1217904668051505294/webhooks","code":50013,"httpStatus":403,"requestData":{"json":{"name":"WA2DC"},"files":[]}},"msg":"Missing Permissions"}
{"level":30,"time":1710441500070,"pid":15396,"hostname":"Corrosive","version":"v0.10.25","msg":"Exiting!"}
`

**Platform**

 - OS: Windows 11

**Comment by FKLC** [comment]
Are you sure that the bot has all the permissions?
