### ISSUE TITLE
Missing Permissions

### ISSUE THREAD

**Issue by guillermo255** [FKLC/WhatsAppToDiscord#187]
**Describe the bug**
When I invite the bot to my server, the terminal closes.

**To Reproduce**
1. Put bot token in terminal
2. Invite bot to the server

**Expected behavior**
I expected it to create the channel with QR codes to scan

**Logs**
{"level":30,"time":1711668719122,"pid":23016,"hostname":"guillePC","version":"v0.10.25","msg":"Starting"}
{"level":30,"time":1711668719776,"pid":23016,"hostname":"guillePC","version":"v0.10.25","msg":"Update checked."}
{"level":30,"time":1711668719776,"pid":23016,"hostname":"guillePC","version":"v0.10.25","msg":"Conversion completed."}
{"level":30,"time":1711668720197,"pid":22048,"hostname":"guillePC","version":"v0.10.25","msg":"Starting"}
{"level":30,"time":1711668720811,"pid":22048,"hostname":"guillePC","version":"v0.10.25","msg":"Update checked."}
{"level":30,"time":1711668720812,"pid":22048,"hostname":"guillePC","version":"v0.10.25","msg":"Conversion completed."}
{"level":30,"time":1711668773041,"pid":21284,"hostname":"guillePC","version":"v0.10.25","msg":"Starting"}
{"level":30,"time":1711668773549,"pid":21284,"hostname":"guillePC","version":"v0.10.25","msg":"Update checked."}
{"level":30,"time":1711668773550,"pid":21284,"hostname":"guillePC","version":"v0.10.25","msg":"Conversion completed."}
{"level":30,"time":1711668857949,"pid":21284,"hostname":"guillePC","version":"v0.10.25","msg":"Exiting!"}
{"level":50,"time":1711668857948,"pid":21284,"hostname":"guillePC","version":"v0.10.25","err":{"type":"DiscordAPIError","message":"Missing Permissions","stack":"DiscordAPIError: Missing Permissions\n    at RequestHandler.execute (C:\\snapshot\\WhatsAppToDiscord\\out.js)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async RequestHandler.push (C:\\snapshot\\WhatsAppToDiscord\\out.js)\n    at async GuildChannelManager.create (C:\\snapshot\\WhatsAppToDiscord\\out.js)\n    at async Client.<anonymous> (C:\\snapshot\\WhatsAppToDiscord\\out.js)","name":"DiscordAPIError","method":"post","path":"/guilds/1189397199629590619/channels","code":50013,"httpStatus":403,"requestData":{"json":{"name":"whatsapp","type":4},"files":[]}},"msg":"Missing Permissions"}

**Platform**
 - OS: [e.g. Windows, MacOS, Linux]

**Additional context**

**Comment by FKLC** [comment]
Are you sure the bot has all the required permissions? The bot tries to create a category called WHATSAPP, but it doesn't have the required permissions.
