### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ExyExz** [FKLC/WhatsAppToDiscord#190]
idk why but sometimes the application/software just crashed 
(Windows)

**Comment by weskerty** [comment]
the same in linux. A script must be made to reinitialize it if the process stops.

**Comment by rodrigopar99** [comment]
I use this command in linux:
`while true; do ./WA2DC-Linux --skip-update; sleep 2; done`
This prevents crashing most of the time.

**Comment by Ishannaik** [comment]
Add a try catch block in the index is that helps aswell, maybe use chatgpt if u can't code

**Comment by Mod4rchive** [comment]
crash seems to happen when replying to a sticker in whatsapp

**Comment by L-Krieger** [comment]
It works fine for a few hours, after that randomly crashes to desktop and when I try to open it again its window stay opened for 5 seconds then closes

**Comment by FKLC** [comment]
Please send logs. Feel free to reopen with logs
