### ISSUE TITLE
Bot Bg

### ISSUE THREAD

**Issue by JustineLoing** [FKLC/WhatsAppToDiscord#193]
**Describe the bug**
After the bot Log in to the server and create a new channel, the bot not sending the QR Code at control-room
**To Reproduce**
1. Type '...'
2. Interact with the bot
3. See error

**Expected behavior**

**Logs**

**Platform**
 - OS: Windows

**Additional context**

**Comment by Eorxeci** [comment]
Hi, I installed the bot today and encountered the same issue
Regards,

**Platform**

- OS: Ubuntu 22.04

**Comment by Questcraft-Online** [comment]
same :/

Platform

- OS: Ubuntu

**Comment by FKLC** [comment]
Closing this issue as it isn't widely reported, but yes, deleting storage folder might help (it'll require redoing the setup steps and the bot won't be able to continue using the old channels)
