### ISSUE TITLE
disabling oneWay

### ISSUE THREAD

**Issue by Bublifuqk** [FKLC/WhatsAppToDiscord#194]
**Is your feature request related to a problem? Please describe.**
Well yeah, there is no way to disable oneWay, atleast not one that I know of.

**Describe the solution you'd like**
Something simple, like twoWay or disabletwoWay

**Describe alternatives you've considered**
Described above.

**Additional context**
I'm really sorry if there already is a way to disable it or if I'm just retarded.

**Comment by theassemblerguy** [comment]
just write "oneWay disabled" into #control-room.

**Comment by Bublifuqk** [comment]
I thought there must be a way, I really am just blind after all :) (thanks tho)
