### ISSUE TITLE
Webhook doesnt show profile picture except mine

### ISSUE THREAD

**Issue by Ishannaik** [FKLC/WhatsAppToDiscord#199]
I did a fresh install twice and 2 different account and systems and both are having this same exact issue.

**Comment by arespawn** [comment]
This is a baileys issue if and when the maintainer has the time he could update to the latest libraries and it will be probably be fixed

**Comment by Ishannaik** [comment]
> This is a baileys issue if and when the maintainer has the time he could update to the latest libraries and it will be probably be fixed.
> 
> I feel updates to the new libraries including discord js may need lots of refactoring etc to the code so this could take some time.

Can you share the link to this issue if it is opened on baileys

**Comment by Ishannaik** [comment]
I think its spamming in the #you channel my profile picture whenever someone else changes it

**Comment by Mod4rchive** [comment]
you can edit your own node_modules bayleys and compile from there. replace the file in .\node_modules\@whiskeysockets\baileys\lib\Socket\chats.js

```
const profilePictureUrl = async (jid, type = 'preview', timeoutMs) => {
        var _a;
        jid = (0, WABinary_1.jidNormalizedUser)(jid);
        const result = await query({
            tag: 'iq',
            attrs: {
                target: jid,
                to: WABinary_1.S_WHATSAPP_NET,
                type: 'get',
                xmlns: 'w:profile:picture'
            },
            content: [
                { tag: 'picture', attrs: { type, query: 'url' } }
            ]
        }, timeoutMs);
        const child = (0, WABinary_1.getBinaryNodeChild)(result, 'picture');
        return (_a = child === null || child === void 0 ? void 0 : child.attrs) === null || _a === void 0 ? void 0 : _a.url;
    };
 ```

**Comment by Ishannaik** [comment]
This did the trick thank you
