### ISSUE TITLE
Media (Pictures and Files) Dont work in new Update

### ISSUE THREAD

**Issue by dexstar007** [FKLC/WhatsAppToDiscord#2]
Hello, again I just fund since in the updated dependencies all the media stop work like it was working before like you send a Picture into Discord to Whatsapp now only show the link not the actual photo like before.
Audio seems to work fine Files, and Pictures are only the issue.
I think I see the example on go-whatsapp there is some validation now to receive both types of files
I don't now exactly.

I'm complete new on Golang. 

Thanks for this awesome bot again.

**Comment by FKLC** [comment]
Bot doesn't send files to decrease both complexity and internet usage. To send image or file you need to first download it from Discord servers and upload to WhatsApp's, but bot instead just sends link of file to ensure skipping those unnecessary steps.
