### ISSUE TITLE
Sync messages to Discord channel

### ISSUE THREAD

**Issue by Hyper-Smartian** [FKLC/WhatsAppToDiscord#20]
Hi there, im a beginner in coding tbh. I've been working on a Discord server lately and I needed a script to bring one of my whatsapp groups to one of my server channel. You have done a really great job with this script mate. As of registering this issue i have one problem with your script. Im having to run the bot locally due to which it cannot be online 24/7. The messages that are sent while the script is not running are not synced back to the channel when i start the script again. I request you to try to make it so that the old messages get synced when i run the script. Please let me know whether it is possible.

Yours sincerely,
Hyper Smartian

**Comment by Hyper-Smartian** [comment]
Hey, you replied to the other issue that was raised. Are you working on this?
Can you please communicate with me dude.

**Comment by FKLC** [comment]
> Are you working on this?

Unfortunately, I'm not. I'm a grade 12 student and I my workload this year is exhausting. I answered that issue because it wasn't particularly a bug, he was just (I guess) congratulating. I will, however, work on this when I have free time.

**Comment by Hyper-Smartian** [comment]
Thanks dude, I do understand you. I'm a class 10 student myself. This server I am working on is for increasing the efficiency of communication within my peer group. Since our school uses good old whatsapp groups to send notifications I was trying to get it into discord. Anyways, thank you very much man!!! I appreciate your work!!!

**Comment by KartSriv** [comment]
@Hyper-Smartian Dude, you can try running it in Heroku or a server in Azure. If you want any help regarding this then here is my discord username: KartSriv#0851.

**Comment by FKLC** [comment]
So I made a little research and it seems possible but it requires too fundamental changes. "One day" I expect to rewrite the whole script but I don't know when, so no promises. I will not close this issue but don't expect and update soon, sorry.

**Comment by FKLC** [comment]
The WhatsApp library used in JS version can't do this at the moment and this feature is hard to implement. You can't load too old messages with the multi-device version anyway, so I'm closing this issue for now.
