### ISSUE TITLE
QUESTION: is installing by package manager a option?

### ISSUE THREAD

**Issue by MrT-tak** [FKLC/WhatsAppToDiscord#201]
Hi, 
im looking to deploy this in ubuntu server so im wondering 
if we can use package managers like:
Apt, etcs

 Thanks.
Me

**Comment by weskerty** [comment]
i use on debian 12. need nodejs. apt install nodejs

**Comment by MrT-tak** [comment]
I want to contain it

**Comment by MrT-tak** [comment]
My original question was wrong
