### ISSUE TITLE
Forwarding Messages from Other Bots

### ISSUE THREAD

**Issue by weskerty** [FKLC/WhatsAppToDiscord#204]
I have added widgetbot which can allow guest posting, I wanted to test that feature in conjunction with WA2DC, but the widget bot message is not forwarded in wpp. WA2DC ignores the second bot message. Is there any setting that can be changed to allow this?

![image](https://github.com/user-attachments/assets/93adc148-579c-4830-902b-54790245c957)
![image](https://github.com/user-attachments/assets/70fae2bc-75e7-42c3-94e1-27e5852eb970)

**Comment by FKLC** [comment]
That can be done, and I'll keep this bug open, but I advise against it as WhatsApp don't approve bots. IIRC we actually ignore all bot messages, so it is weird that it sends the first message.

**Comment by weskerty** [comment]
> so it is weird that it sends the first message.

I think the image is confusing. The WhatsApp bot is WiskaEnterprise and my user account is MarcoRota, who sent the [[[[ and f

The cut is unnecessary. WiskaEnterprise actually did not send anything, it should have sent the "dedos" of the user "hola", but it did not send it because it is a bot.

**Comment by FKLC** [comment]
Can you try the new command `redirectWebhooks yes`? Feel free to reopen the issue.
