### ISSUE TITLE
Add New Groups to Whitelist

### ISSUE THREAD

**Issue by weskerty** [FKLC/WhatsAppToDiscord#206]
When the bot starts it adds the list of chats where messages are sent, but if you use addwhitelist the new groups no longer appear as channels. How to add new groups to the white list without deleting the entire white list so that the channels are generated?

How to generate a new channel from a new group that is not on the white list

**Comment by FKLC** [comment]
I haven't tested it but can you try doing `start <group name or phone number>` then `addToWhitelist #<channel name>`? I think it should work but I'm also not sure

**Comment by weskerty** [comment]
> start <group name or phone number>

Thank you very much, start (group name) works perfectly.

**Comment by FKLC** [comment]
no problem closing the issue as resolved
