### ISSUE TITLE
Yees

### ISSUE THREAD

**Issue by Hooyo129** [FKLC/WhatsAppToDiscord#210]
**Describe the bug**

**To Reproduce**
1. Type '...'
2. Interact with the bot
3. See error

**Expected behavior**

**Logs**
If needed add your logs.txt after redacting any private information.

**Platform**
 - OS: [e.g. Windows, MacOS, Linux]

**Additional context**

**Comment by Hooyo129** [comment]
Good idea

**Comment by FKLC** [comment]
spam?
