### ISSUE TITLE
No Linux installation guide!

### ISSUE THREAD

**Issue by Stradios** [FKLC/WhatsAppToDiscord#214]
I'm writing to request the addition of a Linux installation guide in the documentation for FKLC/WhatsAppToDiscord. Many users rely on Linux, and this guide would greatly enhance their experience.

Additionally, the current documentation lacks instructions on how to run the software after installation. Clear usage guidelines are essential for user satisfaction.

Lastly, could you confirm whether the software can be run in a Docker container? If so, instructions for this setup would be helpful.

Thank you for considering these suggestions.

**Comment by FKLC** [comment]
I added a rant-y installation steps. Thank you for bringing this up.
