### ISSUE TITLE
Send messages to WhatsApp chat directly from Discord Webhooks/APIs

### ISSUE THREAD

**Issue by malagoni** [FKLC/WhatsAppToDiscord#217]
I've been trying to integrate WA2DC along with my personal Bot that is linked with many services through API.

Those APIs send messages all over my Discord Server, but once I've tried to automate content to be sent from WA2DC channel, the messages are not being sent on the actual WhatsApp chat, I have to copy/paste it on the channel for the msg to go.
Notice that those bot messages are only **TEXT**, no embeds, attachments, GIFs, pretty things, none of that, just plain **TEXT**.

Therefore, a slight adjustment on WA2DC to forward this messages received on the Discord channel via **API/Webhook** directly to the WhatsApp chat would be simply **WONDERFUL**, allowing us to automate basically everything.

I'm not sure if that function is already there or it's me that didn't find, but I believe everyone would benefit from this small upgrade, I know WhatsApp won't allow Bot messaging, but just simple text content wouldn't kill anyone.

**Comment by FKLC** [comment]
Done!

**Comment by malagoni** [comment]
> Done! Don't forget to update to the new version. It will autoupdate during next run

You're the best!!!!

**Comment by FKLC** [comment]
Thank you be sure to run `redirectWebhooks yes` to enable it.
