### ISSUE TITLE
Not sending whatsapp QR code after control-room was created

### ISSUE THREAD

**Issue by WuDii0818** [FKLC/WhatsAppToDiscord#220]
The bot did not send out whatsapp QR code after it created the control-room

![Screenshot 2024-11-27 084912](https://github.com/user-attachments/assets/2f707920-fefd-49c6-90bd-8d3c087a0689)

**Comment by FKLC** [comment]
Please upload your logs or email them me@fklc.dev

**Comment by WuDii0818** [comment]
found out it was discord permission issue, have to enable Privileged Gateway Intents under discord developer

**Comment by FKLC** [comment]
Closing as it looks like it's resolved
