### ISSUE TITLE
forward messgage by bot as well

### ISSUE THREAD

**Issue by WuDii0818** [FKLC/WhatsAppToDiscord#221]
Currently, the W2D bot will forward all messages sent by users on Telegram to WhatsApp, however when another bot sends a notice/message it won't forward it. Is it possible to forwards messages by another bot?

**Comment by FKLC** [comment]
please check commands page. https://wa2dc.fklc.dev/#/commands?id=redirectwebhooks

**Comment by WuDii0818** [comment]
the message couldn't be sent, here is the log error :
{"level":40,"time":1732674711746,"pid":26532,"hostname":"LAPTOP-0JH5A9I7","version":"v0.10.28","attrs":{"from":"120363372359494780@g.us","class":"message","id":"3EB040E171A32E504684C2","phash":"2:Htv9SxuR","count":"1","t":"1732674711"},"msg":"could not send message again, as it was not found"}

**Comment by FKLC** [comment]
This log is from baileys. Since I can't reproduce I can't help https://github.com/WhiskeySockets/Baileys/blob/8333a25fca7fc5bf32d4a4196ea91a3895f3aa42/src/Socket/messages-recv.ts#L938

**Comment by malagoni** [comment]
Big UP to this request.

The redirectWebhooks command will literally redirect only webhooks created to the specific channel on Discord Channel settings.
If a BOT/APP command is used on a conversation channel, the returned information is not being sent to WhatsApp chat, note that it's only plain text.

The webhook works perfectly, but for BOT automations this adjustment would be perfect.
![{1110BDC4-1845-49D3-A41B-16CF822E8BA4}](https://github.com/user-attachments/assets/3b9d7d85-b238-46c6-b412-33ed5142bb69)

![{CDA17947-E9B4-4CA5-AA09-76BFB9614439}](https://github.com/user-attachments/assets/c7273d3e-cc58-44f0-b8c1-5d852d6eb9e9)

**Comment by malagoni** [comment]
> Big UP to this request.
> 
> The redirectWebhooks command will literally redirect only webhooks created to the specific channel on Discord Channel settings. If a BOT/APP command is used on a conversation channel, the returned information is not being sent to WhatsApp chat, note that it's only plain text.
> 
> The webhook works perfectly, but for BOT automations this adjustment would be perfect. ![{1110BDC4-1845-49D3-A41B-16CF822E8BA4}](https://private-user-images.githubusercontent.com/20099175/390281067-3b9d7d85-b238-46c6-b412-33ed5142bb69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2ODc0MzUsIm5iZiI6MTczMjY4NzEzNSwicGF0aCI6Ii8yMDA5OTE3NS8zOTAyODEwNjctM2I5ZDdkODUtYjIzOC00NmM2LWI0MTItMzNlZDUxNDJiYjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA1NTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MmMzNjc0MjI0M2YwOTNhOWNjNGM2YjdhYWIzYWY5MDRiZTU0MjhjOWU0M2YzZjc1MDI4YWE2YzViOTE3OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5I2UpgmnwHbitrEyxrhWzy618K-S9lzp-ZRxGr08RZM)
> 
> ![{CDA17947-E9B4-4CA5-AA09-76BFB9614439}](https://private-user-images.githubusercontent.com/20099175/390281000-c7273d3e-cc58-44f0-b8c1-5d852d6eb9e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2ODc0MzUsIm5iZiI6MTczMjY4NzEzNSwicGF0aCI6Ii8yMDA5OTE3NS8zOTAyODEwMDAtYzcyNzNkM2UtY2M1OC00NGYwLWI4YzEtNWQ4NTJkNmViOWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA1NTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NzRlOWQ5YzI4NjJmNTdmZmVhZjZhNjhmNWVkM2QyMWM0MmFiOGEzNDAxMDNkOGRiMWM4OWY2ZjE3NWI1ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9sfFa0BjiQM0AgvWyAvwFiQyAwUKvPxEmkno9QhKXl8)

Also, just one more suggestion.  Activating a Discord Bot with messages sent from WhatsApp would be absolute perfection. 
Example: user sends a command from WhatsApp to Discord > "/command test", activates the Discord bot function and the response is also sent back to WhatsApp chat.
