### ISSUE TITLE
UPX Compressed Binary is Recognized as a Virus

### ISSUE THREAD

**Issue by FreshImmuc** [FKLC/WhatsAppToDiscord#24]
Mc afee blocks the file and when i add it to the Whitelist and execute it, then its stopped directly by Mcafee... idk how to fix it and why is it blocked???

**Comment by FreshImmuc** [comment]
also where do i paste the Bot token in?

**Comment by FKLC** [comment]
Bot asks you to enter token once it runs. For MacAfee I don't use it and don't have any info about it but maybe this can help https://service.mcafee.com/webcenter/portal/cp/home/articleview?articleId=TS102056.

**Comment by FreshImmuc** [comment]
Okay, how do i set a Whitelist? Btw Whitelist means that just one chat is displayed in Discord right?

**Comment by FKLC** [comment]
Adding to whitelist is explained in the README file. Yes, adding to whitelist will make you only receive from that person/channel.
