### ISSUE TITLE
The bot is unresponsive to the commands

### ISSUE THREAD

**Issue by Maximilian-tek** [FKLC/WhatsAppToDiscord#25]
Sorry to reach out to you in that way!
I am struggling with the features advertised. 

I just installed everything and I can receive messages, but where can I use the commands? The console does not accept any, and in the control-room my commands would not be recognized. Am I missing anything?

**Comment by FKLC** [comment]
Hi, are you using a prefix? If you do, you should not be. When the bot connects, does it send message to control-room? If not check settings.json and confirm the channelID for control-room.

**Comment by Maximilian-tek** [comment]
Yeah. I got WhatsApp connection succesfully made! And thats the only output in the control-room. I do not use any kind of prefix. But I got no response when I use any of the commands.

**Comment by FKLC** [comment]
I mean I really don't know what causes this to be honest. Message listeners for Discord are initialized before the WhatsApp connection, so handling commands should work fine if you receive the "WhatsApp connection successfully made!" message. I wish I could help but I don't have a solution for this issue. Sorry.

**Comment by Maximilian-tek** [comment]
Okay, thanks for your time!

**Comment by FKLC** [comment]
What I can recommend for starting a new conversation would be is, run the bot and send the first message through your phone and the bot will catch it and create a new channel on Discord.
