### ISSUE TITLE
Load/Sync old messages

### ISSUE THREAD

**Issue by Neur0nz** [FKLC/WhatsAppToDiscord#27]
is it possible to load all the messages that were sent previously from a WhatsApp group?

**Comment by Furuflame** [comment]
The Exe-Application "WA2DC" has to be running, so that the Bot is running, right?
And is it normal, that I have to insert my Bot-Token again after a restart?

Have a nice day.
Robert

**Comment by FKLC** [comment]
Unfortunately, the bot cannot load old messages now. I plan to implement it one day, but due school I cannot spend much time on coding. Thanks for your suggestion.

**Comment by FKLC** [comment]
I'm closing this issue as it is the duplicate of #20.
