### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by txxr** [FKLC/WhatsAppToDiscord#28]
Hi,
this is a nice and usefull project but i wish it will run at Linux for Example at Raspberry OS at Raspberry Pi.
thx

**Comment by FKLC** [comment]
It should run on Linux, you just have to compile. I don't own a Linux computer, but you can compile for yourself by running `go build WA2DC.go`, if you have [Go](https://golang.org/) installed of course.

**Comment by Filipe-Souza** [comment]
@txxr you can build it normally, just do not use the .bat file.

Open the terminal application, navigate through the source code directory and type:

```bash
go build -ldflags="-s -w" -o wa2dc WA2DC.go
``` 

Where the **-o wa2dc** it's the executable name you want.

I will test with my Armbian system and tell the results. Tested on go version go1.15.7 darwin/amd64 for now

**Comment by FKLC** [comment]
Filipe Souza answered the question in detail. Thanks @Filipe-Souza!
