### ISSUE TITLE
bot token

### ISSUE THREAD

**Issue by deadkid14** [FKLC/WhatsAppToDiscord#3]
when i put the bot token in the exe it doesn't do anything

**Comment by FKLC** [comment]
Are you sure the bot is on the server? If not please follow these steps: 

1. Open a new tab and paste this URL but don't navigate to it. `https://discordapp.com/oauth2/authorize?client_id=INSERT_CLIENT_ID_HERE&scope=bot&permissions=8208` 
1. Move back to **"General Information"** section and copy **"CLIENT ID"**
1. Paste **"CLIENT ID"** to **INSERT_CLIENT_ID_HERE** in the URL you opened in new tab and navigate to it.
1. Accept bot to your server (Recommendation: Create new server for privacy)

**Comment by deadkid14** [comment]
> 1. https://discordapp.com/oauth2/authorize?client_id=INSERT_CLIENT_ID_HERE&scope=bot&permissions=8208

thanks
