### ISSUE TITLE
download failed with status code 404

### ISSUE THREAD

**Issue by MajorShaan** [FKLC/WhatsAppToDiscord#34]
[logs.txt](https://github.com/FKLC/WhatsAppToDiscord/files/6456305/logs.txt)

i don't know why but after doing all steps the commands does not work 
plz help

i tried running WA2DC.exe as admin but nothing changed 

is this because of awast antivirus

**Comment by FKLC** [comment]
It probably isn't about your antivirus, but I don't know why either. Looking at your `logs.txt` file, I see that the bot tries to download files from WhatsApp and fails, but this should not cause any problem with handling commands. Are you still having this issue? Did you make changes to the bot's permissions? This is the only thing I can come up with. Sorry.
