### ISSUE TITLE
Log file has 310 GB in a day

### ISSUE THREAD

**Issue by IOplus** [FKLC/WhatsAppToDiscord#35]
There's nothing much to say. Yesterday I installed the bot on my Discord server, for me and my friends, whitelisted only one chat and kept it there in the background. I wake up today with my drive full...

**Comment by FKLC** [comment]
First of all, I'm really sorry and secondly, I added limit on maximum log entries, so now it shouldn't get that big... If you download the latest version it should not log more than 1000 entries which is probably more than enough. I'm sorry for the inconvenience, again. Closing the issue for now. Feel free to open new issues in the future.

**Comment by IOplus** [comment]
I've seen it. Thanks dude, you've done a really great job with this program, I use it on my discord channel.
I have some ideas and improvements that I'll soon suggest; actually I'm thinking of trying to fork it and test myself, but I would need to learn how to program in GO language, if it's similar to C++ I'll sure do it when I have time.
Thanks again, you're awesome.
