### ISSUE TITLE
Remember category for chats

### ISSUE THREAD

**Issue by IOplus** [FKLC/WhatsAppToDiscord#36]
This is not an issue, it's more of an idea.
The thing is, I create the chat and whitelist it, and then I wanna move it to a different category, and that works fine, no problem, it still works in that category. But if I close the program and reopen it, it will look for the chat inside the default category and doesn't find it, so it creates another one.
You could make it remember the category for each individual chat, or make the program search the entire server. It would be perfect.
Thanks in advance for the attention.

**Comment by FKLC** [comment]
The latest version should work. Thanks for the recommendation!
