### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by IOplus** [FKLC/WhatsAppToDiscord#37]
First of all, thanks for all your hard work. You always try to work on my ideas and fix stuff as fast as you can.

So, I have some ideas. I know you're a busy guy, I've seen your answer to that other guy, but I don't know how to code in GO, so for now I'll leave these suggestions to you, and you can try to do it IF you want WHEN you want.

1. Simplify the whitelist commands, with something like this:
- whitelist add;
- whitelist remove;
- whitelist list.
Instead of one individual command for each.

2. Add a help command;

3. Implement the message text (if there is any) when images are sent (as of now the images are shown without the message text);

4. Implement replies. Something like:
if (the message is a reply to another message) then
     embed this other message text in the current message;

5. Implement sticker support (as of now stickers are not shown);

6. Implement mentions with the @ symbol (this one I imagine it will be harder than the others to implement, if it's even possible).

That's it. With these implementations the bot would be perfect.

**Comment by Utsav-Murudi** [comment]
Hey! I don't understand what "whitelist"ing means exactly. Can you please explain it to me....

**Comment by IOplus** [comment]
Sure. If you have chats on your whitelist, it will sync and create chats on discord only for those chats that you whitelisted; while if you don't, it will sync all your chats. That's basically it.
________________________________

**Comment by FKLC** [comment]
With the latest version, your 1. request isn't possible. second and third requests are already implemented. your fourth request is partially implemented. Stickers are supported as well. I'll keep in mind the sixth request. For now I'm closing the issue.
