### ISSUE TITLE
Still can't move out of default category

### ISSUE THREAD

**Issue by IOplus** [FKLC/WhatsAppToDiscord#39]
For some reason, as soon as I move out of the default category it doesn't work anymore. When I get a new message it recreates the chat inside the category.

**Comment by FKLC** [comment]
Are you sure that you are using the latest version? I just tried it and it is working. I don't know what may cause this.

**Comment by IOplus** [comment]
I'm sure, it's updated.

**Comment by FKLC** [comment]
I still have no clue what causes this and closing this issue as there hasn't been another report of this kind of an issue.

**Comment by esticle** [comment]
Noob user here - however I am running into this as well with the latest release with a couple of issues,

* Do not move a chat to another category and WhatsApp->Discord and Discord->WhatsApp works perfectly fine
* addToWhitelist a chat - move it to another category (keeping permissions) and what I send via WhatsApp is received on Discord but not from Discord to WhatsApp
* addToWhitelist a chat - move it to another category (keeping permissions), restart WA2DC and 'listWhitelist' shows a empty list and the chat appears back in the 'WhatsApp' category and not under the previous category you put it under
