### ISSUE TITLE
Better Documentation Needed

### ISSUE THREAD

**Issue by sohrabhamza** [FKLC/WhatsAppToDiscord#42]
I followed the installation instructions to get it installed and added to my server but the bot keeps jumping from being online to offline, does not respond to any commands and I have no idea how to connect it to Whatsapp web. Please provide better instructions on how to do this.

**Comment by FKLC** [comment]
When you invited the bot did you give all the required permissions? Also, could you try the latest version of the bot to see if it goes on and offline? To connect to WhatsApp, enable multi-device and scan the QR code the bot sends to `#control-channel`
