### ISSUE TITLE
Session couldt restored.

### ISSUE THREAD

**Issue by OldMartin** [FKLC/WhatsAppToDiscord#43]
Session couldn't restored. error decoding login connResp: json: cannot unmarshal array into Go value of type map[string]interface {}
. Going to create a new session!

**Comment by spookycookie27** [comment]
I get same, for a few days now, but I see a PR is up for a small change that may address the problem

**Comment by OldMartin** [comment]
now the program only close after i open

**Comment by FKLC** [comment]
The new version should work, thanks to @rhutikcodes. If that issue happens anytime in the future, you can delete the `sessions.json` file for a quick fix. Feel free to close the issue if it's fixed.
