### ISSUE TITLE
How many chats can I open simulaneously?

### ISSUE THREAD

**Issue by rhutikcodes** [FKLC/WhatsAppToDiscord#44]
After one point the CPU usage becomes full and I am unable to start another chat. Also is it possible to close a chat after sending a message.

**Comment by FKLC** [comment]
I don't know if there is any limitation on how many chats you can open. Deleting channels will remove it from the bot's records too. So, you can close a chat by deleting the channel on Discord. Feel free to close the issue if you don't have any questions related to this issue.
