### ISSUE TITLE
Download fails everytime

### ISSUE THREAD

**Issue by Nishank-25** [FKLC/WhatsAppToDiscord#45]
I don't know why , I am not able to download the .exe file.
![Screenshot 2021-06-30 091947](https://user-images.githubusercontent.com/71635352/123899210-5e8ad780-d984-11eb-8577-c150b3e3cc48.png)

**Comment by FKLC** [comment]
Hi, I don't really know why but AVs detect this(and some other older) version of WA2DC.exe as a virus. You might recover it from your AV or just compile your own WA2DC.exe. I don't know the exact cause of this issue, sorry. As I've said if you feel unsure, feel free to compile for yourself just clone the repo and run `go build -ldflags="-s -w" -trimpath -o WA2DC.exe WA2DC.go`.

**Comment by Nishank-25** [comment]
I am relatively new to git. Can you elaborate on how to compile? Thanks

**Comment by FKLC** [comment]
You have to download this repo from [this link](https://github.com/FKLC/WhatsAppToDiscord/archive/refs/heads/master.zip) and unzip it to a folder. If you have Golang installed, launch a CMD in the folder and run `go build -ldflags="-s -w" -trimpath -o WA2DC.exe WA2DC.go`, it should create an executable called `WA2DC.exe`.

**Comment by Nishank-25** [comment]
Perfect. Its up and running. Thanks
