### ISSUE TITLE
Downloading the latest file is Triggering Windows Virus and threat protection.

### ISSUE THREAD

**Issue by teejavus** [FKLC/WhatsAppToDiscord#47]
WIndows is detecting the following in the newly downloaded file. Trojan:Win32/Trickbot 

![image](https://user-images.githubusercontent.com/46339998/127120863-69b517ca-05d3-4261-ada3-4ec6a91ddde8.png)

**Comment by abhinav-TB** [comment]
same issue

**Comment by spookycookie27** [comment]
I have been using this for a while and examined the code, Just mark it as safe in your virus software.

**Comment by FKLC** [comment]
When I compile my code locally it doesn't get detected as a virus. However, when I download from GitHub it gets flagged for me as well. I guess it has to do with how much it's downloaded or some other algorithm they use. You can always compile your own version by downloading Go. I'm closing this issue now, feel free to reopen if you still have doubts.
