### ISSUE TITLE
HTTP 403 Forbidden, {"message": "Missing Access", "code": 50001}

### ISSUE THREAD

**Issue by Vodoom** [FKLC/WhatsAppToDiscord#51]
The bot was running smooth for a while but then I got hit by this, tried to figure out the issue but couldn't find out why.

**Comment by FKLC** [comment]
Could you try the latest binary and see if you are still having the same issue? If you still have it, would you mind sharing your logs.txt file?

**Comment by mmani648** [comment]
ok
