### ISSUE TITLE
Only certain groups/messages

### ISSUE THREAD

**Issue by avmavairborne** [FKLC/WhatsAppToDiscord#53]
Not an issue per se, but I wanted to know if there's a way I can make this only pull messages from particular chats (i.e., groups or DMs) only.

**Comment by FKLC** [comment]
Hi,

This feature already exists. Could you try the following commands and say whether it works for you?
- `addToWhitelist <channel name>`: Adds specified conversation to the whitelist
- `removeFromWhitelist <channel name>`: Removes specified conversation from the whitelist 
- `listWhitelist`: Lists all whitelisted conversations
