### ISSUE TITLE
Bot goes offline after a couple of seconds

### ISSUE THREAD

**Issue by Progaros** [FKLC/WhatsAppToDiscord#54]
when restarting the old bot this message appears:
```
Session couldn't restored. error decoding login connResp: json: cannot unmarshal array into Go value of type map[string]interface {}
. Going to create a new session!
```

when starting a new bot, the control-room channel gets created and the bot goes offline

**Comment by spookycookie27** [comment]
i have a fix for this.. i was able to apply the fix locally and recompile the app

![image](https://user-images.githubusercontent.com/23298433/140199699-f579cef7-52e7-42a4-ab6a-9ade1a0cc838.png)

**Comment by spookycookie27** [comment]
unfortunately, i do not have permissions to create a branch and pull request for the fix, so I will try to fork and add my fix

**Comment by spookycookie27** [comment]
you can try my forked and updated version here

https://github.com/spookycookie27/WhatsAppToDiscord

**Comment by Progaros** [comment]
Awesome, that fixed it!
Thanks for including itspacchu's version

**Comment by spookycookie27** [comment]
Aye there might be a few issues with mine it was a rush job. IM noticeing an error logged when it makes a connection trying to check the latest version from itspacchu. Ill try to resolve it. It still works though

**Comment by FKLC** [comment]
Thanks @spookycookie27 for maintaining the project in the meantime. @Progaros You can check the new version of the bot if you want to switch to multi-device feature or you can keep using their version.
