### ISSUE TITLE
What does addToWhitelist command do? What does Whitelist exactly mean?

### ISSUE THREAD

**Issue by Utsav-Murudi** [FKLC/WhatsAppToDiscord#56]

**Comment by FKLC** [comment]
Hello, have you seen #37? I think this question has been answered there. Basically, a whitelist only allows the ones on the list to go through, and a blacklist only allows the ones that are not on the list. Whitelist = Allowed, Blacklist = Banned. Once you add someone to the whitelist, you won't get messages from other groups and people except the person/group you added. As it's a list, you can add multiple groups/contacts to it. If you find this explanatory enough please close the issue. If not feel free to ask.

**Comment by Utsav-Murudi** [comment]
Ohh got it. Thanks a lot!
