### ISSUE TITLE
Display Sender Alias Name in Groups

### ISSUE THREAD

**Issue by Progaros** [FKLC/WhatsAppToDiscord#57]
Can you please add the `PushName` to the number if there is no contact? 
So the Name will be: `+012345678 ~UserName BOT` just like like in WhatsApp
Probably in the `jidToName` function

**Comment by FKLC** [comment]
Hi, please see if the latest version is what you wanted. Thanks for the recommendation.

**Comment by Progaros** [comment]
Awesome, looks perfect now!
Thanks a lot :)
