### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cezarlacatus** [FKLC/WhatsAppToDiscord#59]
Hello, I have a question.

I didnt use this bridge and I just want to know if its possible to forward everything is discussed in an watsapp group to a specific discord channel and vice-versa.

Basically peoples in my whatsapp group post sales anouncements and I want them to be forwarded also to my discord channel, and when they post to discord I want for the whatsapp bot to post them in the whatsapp group.

So the question is: I am able to do all of this using this software?

Thank you

**Comment by FKLC** [comment]
Yes, that is possible. Also, if you want to use only one conversation(just your sales whatsapp group) and not the other conversations(your family and friends), you can add it to the whitelist and you won't receive messages from other people.
- Follow the setup instructions [here](https://github.com/FKLC/WhatsAppToDiscord#setup)
- Type `start` and your sales group name in `#control-channel`
- Type `addToWhitelist #<your sales group name>` in `#control-channel`
