### ISSUE TITLE
How do i self host this?

### ISSUE THREAD

**Issue by CemreSuler** [FKLC/WhatsAppToDiscord#6]
I'm trying to get it on my raspberry pi but I can't get it to work at all. It always says "this is your first run".

**Comment by FKLC** [comment]
Program checks if the `settings.json` file exist. Please be sure the program has writing permissions. It doesn't use any platform specific library so it should work on Linux too.

**Comment by CemreSuler** [comment]
I got it to work by changing all tokens in the WA2DC.go file to my own discord tokens. Works perfectly, ty!

**Comment by FKLC** [comment]
That should work for the connection part but to keep the old conversations (`chats.json`) and to not login every time (`session.json`) you need a permanent storage which is the file system for the WA2DC.

**Comment by CemreSuler** [comment]
Well I declared the direct paths for those too. I works perfectly, even after reboots (with systemD)

**Comment by FKLC** [comment]
Thank you for explaining how you solved your issue too. For now I'm closing the issue.
