### ISSUE TITLE
Doesn't list a private chat of WhatsApp

### ISSUE THREAD

**Issue by DRaKuLa89** [FKLC/WhatsAppToDiscord#60]
2021-12-05T11:37:19+05:30 SessionCipher.go:214 ▶  Received message with old counter: 3 , 1
[ERROR] 2021-12-05T11:37:19+05:30 SessionCipher.go:264 ▶  Unable to get or create message keys: Received message with old counter: 3 , 2
[WARNING] 2021-12-05T11:37:19+05:30 SessionCipher.go:214 ▶  Received message with old counter: 3 , 2

this is the error I get

**Comment by FKLC** [comment]
This issue is more about whatsmeow and not about WA2DC. I would suggest asking there.
