### ISSUE TITLE
Forwarded Messages (Not Working?)

### ISSUE THREAD

**Issue by kira-iwnl** [FKLC/WhatsAppToDiscord#62]
Forwarded links , messages , photos or videos being sent to you in groups or in private messages, cannot be read by user thru bot in discord.

For eg, a yt link is forwarded from a person to person to you , you get the link in your whatsapp app but you won't even notice such link being delivered to you in discord.

**Comment by FKLC** [comment]
The latest version should work. Please see if it works. I'm closing the issue now, if it doesn't work, feel free to reopen.
