### ISSUE TITLE
restapi.go:114: error closing resp body

### ISSUE THREAD

**Issue by spookycookie27** [FKLC/WhatsAppToDiscord#63]
Started appearing yesterday?
Bot just crashes now

`08:17:24 restapi.go:114: error closing resp body
08:17:24 restapi.go:114: error closing resp body
08:17:24 WA2DC.go:60: Discord handlers added
08:17:24 WA2DC.go:63: Chats parsed
08:17:24 restapi.go:114: error closing resp body
08:17:25 WA2DC.go:66: Channels repaired
08:17:28 WA2DC.go:104: WARN Unknown connect failure: %s [<failure location="rva" reason="405"/>]
08:17:28 WA2DC.go:103: ERROR Error reading from websocket: %v [websocket: close 1006 (abnormal closure): unexpected EOF]
08:17:28 restapi.go:114: error closing resp body
08:17:28 WA2DC.go:111: runtime error: invalid memory address or nil pointer dereference`

**Comment by Alsgild** [comment]
Same issue

**Comment by FKLC** [comment]
Please check the latest version and let me know if it doesn't fix your issue. Otherwise, feel free to close the issue.

**Comment by spookycookie27** [comment]
You da man!!
I tried to update the dependencies, but wasnt sure about the IsQR and evt.Code.
GO is not my language!
