### ISSUE TITLE
Reply-to in discord

### ISSUE THREAD

**Issue by spookycookie27** [FKLC/WhatsAppToDiscord#65]
Reply-to in discord messages get completely dropped. 
But ReplyTo in whats app seems to work coming back to Discord.

I appreciate you are busy, I'd be happy to help fix little issues like this if you give me pointers. 
I dunno how to debug the app at runtime using VSCode. Not had much experience of Go.

**Comment by Residays** [comment]
Confirming. Same here.

**Comment by KungFuCookie** [comment]
Thanks I will check the latest!

**Comment by spookycookie27** [comment]
Yeah still the same. Hit reply to in Discord, nothing appears in whats app at all.
I can try to debug, if I can figure out how to debug Go at runtime in VsCode

**Comment by FKLC** [comment]
Since I couldn't reproduce the bug, I couldn't try. I rewritten the entire bot, please see if it works.

**Comment by spookycookie27** [comment]
excellent news. I might be able to help maintain this, Go was well out of my comfort zone

**Comment by FKLC** [comment]
Closing the issue for inactivity.
