### ISSUE TITLE
Specified chats & Ease & Online required

### ISSUE THREAD

**Issue by AashvikD** [FKLC/WhatsAppToDiscord#66]
# Issue 1 - Specified chats
### Problem 
I have multiple WhatsApp chats. I only want to share some WhatsApp chats. I can't find any support to select specific chats to use.
### Solution
Please add support to select specific chats for broadcasting

# Issue 2 - Ease
### Problem
I don't understand exactly what each command does. 
### Solution
Could you please elaborate on their description?

# Issue 3 - Online
### Problem
We are required to keep our device online to keep the bot running
### I am unaware of a possible solution.
Except for Heroku, which WhatsApp doesn't allow

**Comment by FKLC** [comment]
- Issue 1: See `addToWhitelist <channel name>` command. After you start a conversation, you simply type `addToWhitelist #<your friend's or group chat's name>`.
- Issue 2: Which command description do you not get? I can try to fix them.
- Issue 3: This just isn't possible. If power usage is a concern maybe run on a raspberry pi or small device, but other than that it is impossible to do it (except as you say running a server which may get your account banned).

**Comment by FKLC** [comment]
Closing the issue as it has been 10 days without a response. Feel free to reopen if needed.
