### ISSUE TITLE
Heroku Discord Auth

### ISSUE THREAD

**Issue by AashvikD** [FKLC/WhatsAppToDiscord#67]
# Heroku has problems

## I don't know which URL I am supposed to open for Discord authentication

# Error Message

Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

# Please tell how to authenticate Discord URL

**Comment by FKLC** [comment]
You bot didn't even start up for some reason. Maybe try sending your logs, BUT it is highly possible that you'll get banned from WhatsApp if you use the bot with Heroku.

**Comment by FKLC** [comment]
Please try with the latest version if you take the risk of getting banned. I'm closing this issue as you haven't replied in 10 days. Feel free to reopen if you need further help.
