### ISSUE TITLE
what is the step after install

### ISSUE THREAD

**Issue by Billy7elal** [FKLC/WhatsAppToDiscord#7]
so i followd the totourial and stuff and the bot sent me a qr code that I scanned with Whatsapp web thing, it didn't work....?

**Comment by FKLC** [comment]
Did you look at [commands](https://github.com/FKLC/WhatsAppToDiscord#commands)? So basically to start you need to type `list` to `control-room`. It will give you, your contacts. Then use the number or name with the command `start` like this: `start <number with country code or name>`

**Comment by nkraja1** [comment]
Is there a way for us to view our contacts as the bot's name? For example the bot will automatically be named "test" if our contacts name is "test" this would be very helpful in groupchats to know who is who. This is similar to what discordsrv does in minecraft.

**Comment by FKLC** [comment]
> Is there a way for us to view our contacts as the bot's name? For example the bot will automatically be named "test" if our contacts name is "test" this would be very helpful in groupchats to know who is who. This is similar to what discordsrv does in minecraft.

This would involve webhooks which is not what W2DC is built on but I'll look at it. Thanks for feedback!

**Comment by nkraja1** [comment]
Another wild and most likely not possible suggestion: create a channel where discord users could send and receive messages from the whatsapp group chat almost as if the whatsapp group chat is on discord. I don't know how this could possibly work but it is at least fun to think about.

**Comment by FKLC** [comment]
Bot doesn't set any permission for channels it create, which means it is up to the server owner to choose who will/won't see the chat. However, sending messages with prefixes wouldn't fit WhatsApp users anyway. Another way might be allowing everyone to login with their WhatsApp, but that's not something I would want to implement anyway. Thanks for feedback anyway!

**Comment by FKLC** [comment]
> Is there a way for us to view our contacts as the bot's name? For example the bot will automatically be named "test" if our contacts name is "test" this would be very helpful in groupchats to know who is who. This is similar to what discordsrv does in minecraft.

@nkraja1 Done!

**Comment by nkraja1** [comment]
Oh wow! I didn't expect that to happen to quickly!

**Comment by nkraja1** [comment]
It does not appear to be showing the name of the contact. Should I do a full uninstall and reinstall? Also does the download link have the updated exe?

**Comment by FKLC** [comment]
> It does not appear to be showing the name of the contact. Should I do a full uninstall and reinstall? Also does the download link have the updated exe?

You should have first downloaded the new release but anyway I just realized a bug and deleted it. I'll fix it as soon as possible.

**Comment by FKLC** [comment]
Published new release. Should work now. [Download](https://github.com/FKLC/WhatsAppToDiscord/releases/tag/v0.2.2-alpha) the new binary. Just replace with the existing one. Also, don't forget to give "Manage Webhooks" permission to the bot.
@nkraja1

**Comment by Billy7elal** [comment]
so i deleated the discord server with the bot on it, and i deleted wa2dc and reinstalled it, now when i open it again it closes instantly, is there anything that can be done about this

**Comment by FKLC** [comment]
Is the folder empty? If not, first delete `session.json` and `chats.json`, then try again.

**Comment by Billy7elal** [comment]
what folder..
i only see the wa2dc.exe

**Comment by FKLC** [comment]
To be honest, I don't know the fix neither the problem. Can you run it through command line/terminal?

**Comment by nkraja1** [comment]
I know what is problem is. All he has to do is place the exe in a new folder and everything will work.

**Comment by FKLC** [comment]
> I know what is problem his. All he has to do is place the exe in a new folder and everything will work.

The only thing this can fix is corrupted JSON files. And according to @Billy7elal there is not any other file

> what folder..
> i only see the wa2dc.exe

But definitely it's worth a try.

**Comment by nkraja1** [comment]
> Published new release. Should work now. [Download](https://github.com/FKLC/WhatsAppToDiscord/releases/tag/v0.2.2-alpha) the new binary. Just replace with the existing one. Also, don't forget to give "Manage Webhooks" permission to the bot.
> @nkraja1
> 
> > It does not appear to be showing the name of the contact. Should I do a full uninstall and reinstall? Also does the download link have the updated exe?
> 
> Also, if you are receiving messages but not with their names, then you probably didn't install the latest version. Because bot won't send messages unless it has access to webhooks (for group chats only).

Oh so the names will only show for group chats? I was testing it with dm and it wasnt working with the latest version so ill try group chats next.

**Comment by FKLC** [comment]
> Oh so the names will only show for group chats? I was testing it with dm and it wasnt working with the latest version so ill try group chats next.

Yeah... I don't know why I didn't do the same for the DM's but soon I'll release a new version with corrupted JSON and channel checker, and fix that too.

**Comment by nkraja1** [comment]
Oh, nice, That will be very useful.

**Comment by Billy7elal** [comment]
ok i deleated it once more and reinstalled it and I have a settings.json file that I can edit, so I changed the bot token from there... is that what I should be doing

**Comment by FKLC** [comment]
I'm sorry but I can't understand at what step you are on. The [setup tutorial](https://github.com/FKLC/WhatsAppToDiscord#setup) should set the bot up and running. If you already have your settings.json file, your next step should be running and inviting bot to your server.

**Comment by Billy7elal** [comment]
i do have the setting.json file but I wanted to use a different bot so I changed the "token" to the correct token, I than went on with the totourial and added the bot to the server, i had to add a step because you cant change the bot token? so now its not displaying a qr code

**Comment by FKLC** [comment]
Was the bot running, when you invited it? If it wasn't you have to populate fields in the settings.json by yourself, or just kick the bot and invite it while the bot is running (you have to delete settings.json if you will kick it).

**Comment by Billy7elal** [comment]
how would i know if the bot is running is there an indicateor... what do i need to add to the settings.json for it to work

**Comment by FKLC** [comment]
Your `settings.json` should look like this:
```json
{
    "Token": "Your bot token",
    "GuildID": "Your Guild/Server ID",
    "CategoryID": "A category ID, to put your WhatsApp chats under. See in the image there is a field called 'WHATSAPP', it is a category example",
    "ControlChannelID": "A channel ID to control your bot. 'control-room' in the image",
    "SessionFilePath": "session.json",
    "ChatsFilePath": "chats.json",
    "WebhooksFilePath": "webhooks.json",
    "SendErrors": false
}
```
![image](https://user-images.githubusercontent.com/29578493/86158465-d0f97b00-bad6-11ea-91de-36e99df5d017.png)

**Comment by FKLC** [comment]
But I would suggest first copy your bot token and kick the bot. Then delete `settings.json`, run the bot again, and paste your token again, keep it running. Lastly invite the bot to the server again and it should do the rest.

**Comment by Billy7elal** [comment]
do i need to open the .exe with administrative permissions, because i deleted settings.json and reopend the .exe and when i press enter nothing is happening

**Comment by FKLC** [comment]
No you don't need to run with admin perms. If it closes itself immediately, I suspect it runs into an issue. Can you run it through command line/terminal and type the output here?

**Comment by Billy7elal** [comment]
it dosent close immediately however it stays open after i press enter

**Comment by FKLC** [comment]
Yes that's an expected behaviour. At this point you should invite the bot to the server.

**Comment by Billy7elal** [comment]
so i paste the bot token, press enter close the executeable than continue with the tutorial..?

**Comment by FKLC** [comment]
No, don't close the executable it should be running. And yeah continue with the step 8.

**Comment by Billy7elal** [comment]
ok !
