### ISSUE TITLE
Discord Image to Whatsapp Broken

### ISSUE THREAD

**Issue by Sodies** [FKLC/WhatsAppToDiscord#72]
Its not possible to send image from discord to whatsapp
It will received a link instead of image in whatsapp

**Comment by FKLC** [comment]
Yes this is an expected behavior to prevent uploading images twice(one in discord and one in whatsapp). I may implement a way to do this, but I can't promise.

**Comment by FKLC** [comment]
Please see the new version. The new version does what you explain. I'm closing the issue now. If there is a problem feel free to reopen.
