### ISSUE TITLE
Bot is broken

### ISSUE THREAD

**Issue by Craftgeeking** [FKLC/WhatsAppToDiscord#73]
Hello ! Thank you very much for this IRC , we really needed a way to connect discord to whatsapp and you made it possible ! 

About my issue ; the bot is broken and now reply only with the error :
Couldn't find the user. Restart the bot, or manually delete this channel and start a new chat using the start command.
Even after 3 fresh install ( the server, the application and even 8 times for the bot.... ) it doesn't work anymore .

To reproduce : 
1. Have already done the code QR scan step previously ( and if you have the same problem as me the bot should have crashed )
2. Run the bot
3. Paste bot token and open invite url in browser 
4. The bot is joining ( and is creating double channels and double categories, minor issue but i should let you know )
5. Ask **list** or **resync** and the bot will respond with : Couldn't find the user. Restart the bot, or manually delete this channel and start a new chat using the start command.
6. Restarting the bot sometimes work sometimes not 
7. Whan asked the ping with command **ping** it goes between 300-350 ms is the bot targeting the wrong servers ?

**Comment by KungFuCookie** [comment]
Yes I am experiencing similar issues, had to revert to the old GO version

**Comment by FKLC** [comment]
Please see if latest version of the bot it working. Made some fixes.

**Comment by FKLC** [comment]
> 7. Whan asked the ping with command **ping** it goes between 300-350 ms is the bot targeting the wrong servers ?

Since the bot runs on your local computer, and the message timestamps are from Discord's servers, there is a sync issue. It can be fixed, but I wanted to keep things simple for that command. Resync your computer's time. Check this website to see if your computer time is behind https://time.is/ (even little differences matter since it's in ms.)

**Comment by FKLC** [comment]
Closing the issue due to inactivity. Feel free to reopen.
