### ISSUE TITLE
Commands and the bot

### ISSUE THREAD

**Issue by Tojie2000** [FKLC/WhatsAppToDiscord#74]
Sry, new to the bot, just to specify, the bot works, i can speak to someone through discord to whatsapp, though i cannot figure out how to use commands, also probably due to the fact that every time i message in control room the bot says "Couldn't find the user. Restart the bot, or manually delete this channel and start a new chat using the start command." but i cant even find out how o use the start comand, tried using /start, .start, start by its self, used almost all of the other commands like this and nothing worked, may be a glitch/bug, might be me just being a dumbass, either way, need help or to get this fixed :)

**Comment by FKLC** [comment]
Please see if latest version of the bot it working. Made some fixes.

**Comment by FKLC** [comment]
Closing the issue due to inactivity. Feel free to reopen.
