### ISSUE TITLE
Bot Seem to just crash 

### ISSUE THREAD

**Issue by itspacchu** [FKLC/WhatsAppToDiscord#75]
The latest release just seem to crash after launching it.

```It seems like this is your first run.
Please enter your bot token: REMOVE
Invite the bot using the following link: REMOVE
Bot is now running. Press CTRL-C to exit.
/snapshot/WhatsAppToDiscord/src/whatsapp_utils.js:126
                        return { channelJid: formatJid(msg.key.remoteJid), senderJid: formatJid(state.waClient.user.id) };
                                                                                                                    ^

TypeError: Cannot read properties of undefined (reading 'id')
    at Object.getWebhookAndSenderJid (/snapshot/WhatsAppToDiscord/src/whatsapp_utils.js:126:96)
    at Client.<anonymous> (/snapshot/WhatsAppToDiscord/src/discord_manager.js:38:50)
    at Client.emit (node:events:527:28)
    at /snapshot/WhatsAppToDiscord/src/whatsapp_manager.js:53:49
    at new Promise (<anonymous>)
    at EventEmitter.<anonymous> (/snapshot/WhatsAppToDiscord/src/whatsapp_manager.js:53:11)

Node.js v17.8.0
ubuntu@instance-20211229-1549:~/wa2discord$ ./WA2DC-Linux
It seems like this is your first run.
Please enter your bot token:
```

Machine details
```
ubuntu@instance-20211229-1549:~/wa2discord$ uname -a
Linux instance-20211229-1549 5.11.0-1028-oracle #31~20.04.1-Ubuntu SMP Wed Jan 26 14:17:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by FKLC** [comment]
Pushed a new version. Please see if it is working.

**Comment by FKLC** [comment]
Are you running the bot on a server? If so, which provider are you using? I heard people getting banned for running WhatsApp bots on non-residential IPs. Were you able to run the bot without getting banned? I'm asking because sometimes people ask how to run the bot on a server, so it might be useful for them.

**Comment by KungFuCookie** [comment]
totally interested to see the answer here. I was about to push to Digital Ocean droplet until FKLC put the fear of god into me....

**Comment by itspacchu** [comment]
I am using Oracle free tier to run it , I set it to same region as where I live since there was an option so never gave me any problem.

**Comment by spookycookie27** [comment]
The new JS version keeps disconnecting, are you finiding that a problem running on Oracle? DO you have a link to the free tier?

**Comment by itspacchu** [comment]
> The new JS version keeps disconnecting, are you finiding that a problem running on Oracle? DO you have a link to the free tier?

https://www.oracle.com/cloud/free/ @spookycookie27

**Comment by mikimite** [comment]
Hi,

I just set this on a LXC container rocky linux 9 under proxmox configured as a systemd daemon. I saw the service stopping at somepoint but systemd restarted, so no issues at all and no downtimes.

Thanks @FKLC  for the work

**Comment by weskerty** [comment]
> The new JS version keeps disconnecting, are you finiding that a problem running on Oracle? DO you have a link to the free tier?
You can use a script to start it automatically every time it closes.
I use it on Termux proot Debian.

all.sh
```
#!/bin/bash

# Scripts
carpeta="$HOME/script/"

iniciar_script() {
    bash "$1" &
    echo "Script $1 iniciado."
}

verificar_ejecucion() {
    if ! pgrep -f "$1" >/dev/null; then
        echo "$1 se detuvo. Esperando a reiniciar..."
        sleep 300  # Esperar 5 minutos (300 segundos)
        echo "Reiniciando el script $1..."
        iniciar_script "$1"
    fi
}

main() {
    cd "$carpeta" || exit 1
    for script in *.sh; do
        iniciar_script "$script"
    done
    while true; do
        for script in *.sh; do
            verificar_ejecucion "$script"
        done
        sleep 30 
    done
}
main

```
The /script/ folder should have all the scripts that you need to start and not close. Example WA2DC;

wadc.sh
```
#!/bin/bash
cd $HOME/wadc/
npm start .
```
For example, I use it on a Redmi Note 8, which when turned on automatically starts Termux which is configured to start update.sh (updates the bots) and then calls ./all.sh which is this script and starts the bots, then tasker repeats opening whatsapp and termux in case of closing and due to the 14-day WhatsApp limitation. That would be the most automatic possible in my opinion.

**Comment by sambakura** [comment]
@weskerty Hey. How did you run it on Termux? Im new to all that stuff and trying for 2 days now to run it with Termux on my s22 Ultra. Whould you mind explain that to me? 😅

**Comment by sambakura** [comment]
Nvm i did it finally. I loaded the script in nano ~/.bashrc so that it starts everytime i open Termux. Than i use tmux to let it run in the background till i stop it. Damn usefull tho. Ty for youre work @FKLC

**Comment by weskerty** [comment]
> Nvm i did it finally. I loaded the script in nano ~/.bashrc so that it starts everytime i open Termux. Than i use tmux to let it run in the background till i stop it. Damn usefull tho. Ty for youre work @FKLC

Above your comment I put a script that restarts the processes in case they are closed.
In termux I use proot-distro debian to make it work since sharp required by baileys is not for the "android" platform which is how termux identifies itself.
