### ISSUE TITLE
Doesnt recognize my bot token

### ISSUE THREAD

**Issue by Sodies** [FKLC/WhatsAppToDiscord#76]
Im currently using the latest version of the software. I key in my bot token but but no response from my discord channel. Normally it should appear a control room channel but now theres none after i updated.

**Comment by Sodies** [comment]
yes it does tell me to invite the bot. But the bot is already in. I put it in a new folder. After i key the token and tells me to invite the bot I close it and reopens it and it ask me to key the token again.

**Comment by Sodies** [comment]
i reinvite the bot. Now it works. Thanks

**Comment by Sodies** [comment]
I have a question. If I have 3 whatsapp i wanna use. How do i assign them? Because I can only open 1 whatsapptodiscord software.

**Comment by Sodies** [comment]
Whenever I try to open another whatsapptodiscord software it instantly close itself

**Comment by FKLC** [comment]
It should be working now. Closing the issue. Feel free to reopen if needed.
