### ISSUE TITLE
bot crashing and token saving

### ISSUE THREAD

**Issue by SukhSinghOberoi** [FKLC/WhatsAppToDiscord#77]
the bot crashes quite often and whenever i restart the bot it asks for the token everytime and i have to kick the bot and readd it to the server for it to work. should i send the log file here? (im kinda a noob to this stuff btw)

**Comment by spookycookie27** [comment]
same, Im still using GO version.

**Comment by FKLC** [comment]
> same, Im still using GO version.

Go version is no longer supported. JS version is stable at the moment. @SukhSinghOberoi are you also using the Go version?

**Comment by spookycookie27** [comment]
from the terminal on macOS

`Last login: Thu Jun 23 23:16:44 on ttys002
xxx@xxxxxxx WA2DC JS Version % ./WA2DC-macOS
It seems like this is your first run.
Please enter your bot token: OTg5NjU2NTI4MDY5OTk2NTU0.GVVJcD.lOUOHhlai7BZr1g19KowJ3Eo30mmlesGkoH9CM
Invite the bot using the following link: https://discordapp.com/oauth2/authorize?client_id=989656528069996554&scope=bot&permissions=536879120
Bot is now running. Press CTRL-C to exit.
/snapshot/WhatsAppToDiscord/src/whatsapp_manager.js:59
				if (!['conversation', 'extendedTextMessage', 'imageMessage', 'videoMessage', 'audioMessage', 'documentMessage', 'stickerMessage'].some(el => Object.keys(message.message).includes(el))) {
				                                                                                                                                                    ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /snapshot/WhatsAppToDiscord/src/whatsapp_manager.js:59:153
    at Array.some (<anonymous>)
    at EventEmitter.<anonymous> (/snapshot/WhatsAppToDiscord/src/whatsapp_manager.js:59:135)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.1.0
xxxx@xxxxxxx WA2DC JS Version % ./WA2DC-macOS
It seems like this is your first run.
Please enter your bot token: OTg5NjU2NTI4MDY5OTk2NTU0.GVVJcD.lOUOHhlai7BZr1g19KowJ3Eo30mmlesGkoH9CM
Invite the bot using the following link: https://discordapp.com/oauth2/authorize?client_id=989656528069996554&scope=bot&permissions=536879120`

and the logs

`{"level":30,"time":1656022951166,"pid":21751,"hostname":"StevesMacBook","msg":"Starting"}
{"level":30,"time":1656022951617,"pid":21751,"hostname":"StevesMacBook","msg":"Update checked."}
{"level":30,"time":1656022951626,"pid":21751,"hostname":"StevesMacBook","msg":"Initialized database."}
{"level":30,"time":1656022987211,"pid":21751,"hostname":"StevesMacBook","msg":"Loaded settings."}
{"level":30,"time":1656022987212,"pid":21751,"hostname":"StevesMacBook","msg":"Loaded contacts."}
{"level":30,"time":1656022987213,"pid":21751,"hostname":"StevesMacBook","msg":"Loaded chats."}
{"level":30,"time":1656022987887,"pid":21751,"hostname":"StevesMacBook","msg":"Discord client started."}
{"level":30,"time":1656022988245,"pid":21751,"hostname":"StevesMacBook","msg":"Repaired channels."}
{"level":30,"time":1656022988413,"pid":21751,"hostname":"StevesMacBook","msg":"WhatsApp client started."}
{"level":30,"time":1656022988851,"pid":21751,"hostname":"StevesMacBook","browser":["Baileys","Chrome","4.0.0"],"helloMsg":{"clientHello":{"ephemeral":"LOgW6t7Xf8i6p/JL24RMuYx076/UeA8dreiuzcXtFWk="}},"msg":"connected to WA Web"}
{"level":30,"time":1656022988971,"pid":21751,"hostname":"StevesMacBook","msg":"handshake complete"}
{"level":30,"time":1656022988972,"pid":21751,"hostname":"StevesMacBook","node":{"passive":true,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2222,"tertiary":11},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","regData":{"eRegid":"AAAANg==","eKeytype":"BQ==","eIdent":"HQNOAWTcnKVL+TKrNfUCIo3ny7JJxuVbGOJorMfrOzk=","eSkeyId":"AAAB","eSkeyVal":"+hqARhgSoSb3Sm6IYQveSdDvGEp9Uk6E5E+7k16WPTY=","eSkeySig":"TkBRsW4V20JwLSCirefuuFBJYXuPEUyct+mhwGTJrqbqdHYEseAm3NYQ7/3UM7IfetybB93w2nkef68nzp/shA==","buildHash":"iY/3BIuIma3uGZPeXN50dQ==","companionProps":"CgdCYWlsZXlzEgYIBBAAGAAYASAA"}},"msg":"not logged in, attempting registration..."}
{"level":30,"time":1656023069245,"pid":21751,"hostname":"StevesMacBook","jid":"447800967762:41@s.whatsapp.net","msg":"registered connection, restart server"}
{"level":30,"time":1656023069246,"pid":21751,"hostname":"StevesMacBook","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":410,"payload":{"statusCode":410,"error":"Gone","message":"Restart Required"},"headers":{}}},"msg":"connection closed"}
{"level":40,"time":1656023069246,"pid":21751,"hostname":"StevesMacBook","msg":"If your process stalls here, make sure to implement the reconnect logic as shown in https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts#:~:text=reconnect"}
{"level":50,"time":1656023069876,"pid":21751,"hostname":"StevesMacBook","err":{"type":"Error","message":"Restart Required","stack":"Error: Restart Required\n    at WebSocket.<anonymous> (/snapshot/WhatsAppToDiscord/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:433:17)","data":null,"isBoom":true,"isServer":false,"output":{"statusCode":410,"payload":{"statusCode":410,"error":"Gone","message":"Restart Required"},"headers":{}}},"msg":"Restart Required"}
{"level":30,"time":1656023070374,"pid":21751,"hostname":"StevesMacBook","browser":["Baileys","Chrome","4.0.0"],"helloMsg":{"clientHello":{"ephemeral":"/kW+Z6u5OfDP6IpnAqZBucM9LbBosSg7XWZGdJqEaHk="}},"msg":"connected to WA Web"}
{"level":30,"time":1656023070495,"pid":21751,"hostname":"StevesMacBook","msg":"handshake complete"}
{"level":30,"time":1656023070495,"pid":21751,"hostname":"StevesMacBook","node":{"username":"447800967762","passive":true,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2222,"tertiary":11},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","device":41},"msg":"logging in..."}
{"level":30,"time":1656023070676,"pid":21751,"hostname":"StevesMacBook","msg":"uploaded pre-keys"}
{"level":30,"time":1656023070903,"pid":21751,"hostname":"StevesMacBook","msg":"opened connection to WA"}
{"level":40,"time":1656023070904,"pid":21751,"hostname":"StevesMacBook","msg":"no name present, ignoring presence update request..."}
{"level":30,"time":1656023070926,"pid":21751,"hostname":"StevesMacBook","msg":"got 0 offline messages/notifications"}
{"level":50,"time":1656023084299,"pid":21751,"hostname":"StevesMacBook","msgId":"3EB066C6D839006F7F7C","params":["No sender key for: 31683608441-1600466659@g.us::447800967762:38::0"],"msg":"failure in decrypting message"}
{"level":30,"time":1656023084310,"pid":21751,"hostname":"StevesMacBook","name":"Steve","msg":"received pushName"}
{"level":30,"time":1656023112033,"pid":21987,"hostname":"StevesMacBook","msg":"Starting"}
{"level":30,"time":1656023112440,"pid":21987,"hostname":"StevesMacBook","msg":"Update checked."}
{"level":30,"time":1656023112446,"pid":21987,"hostname":"StevesMacBook","msg":"Initialized database."}
`

**Comment by spookycookie27** [comment]
so I deleted all apps in Discord Developers, and all bots. Created a new App, new Bot token, and deleted all previous channels in Discord created by GO version. Ran into immediate problems as you can see. No messages in discord, no new channels created after scanning the QR code in WA.

**Comment by spookycookie27** [comment]
OK I have got it running again on JS version, and Ill post errors/logs

**Comment by Z0MBlI** [comment]
[log.txt](https://github.com/FKLC/WhatsAppToDiscord/files/8975380/log.txt)

**Comment by FKLC** [comment]
@Z0MBlI I checked your logs but unfortunately v0.6.7 doesn't log errors before exit. I pushed a new version and it catches errors before exit. So please run with that version and report back here. I deleted the original comment you made because it included your phone number.

**Comment by FKLC** [comment]
This is normally the case, but when the bot crashes it can't save, and since the bot fails on the first run, it can't save your token info etc. causing you to enter it everytime. If it works for a moment, then run the bot enter your token invite it and then hit control + c to initiate saving the state of the bot before exit.

**Comment by Z0MBlI** [comment]
oh nice thx for help it works

**Comment by Z0MBlI** [comment]
[log.txt](https://github.com/FKLC/WhatsAppToDiscord/files/8983772/log.txt)
can you fix the errors?

**Comment by FKLC** [comment]
@Z0MBlI now the bot saves the state no matter the exit reason. it shouldn't reset everything now.
