### ISSUE TITLE
Executing via cmd

### ISSUE THREAD

**Issue by g0dev** [FKLC/WhatsAppToDiscord#8]
![image](https://user-images.githubusercontent.com/55219735/87747330-9bcc7880-c7b8-11ea-89db-c484ceba0d6a.png)

Crash after add the webwhatsapp session on the device
 
Using Windows 10 Server

**Comment by FKLC** [comment]
Hi @g0dev, this is surely an unexpected behaviour but just to be sure were you using the command `start` without any argument? I've tried to install bot again just like you did and couldn't reproduce the bug. I suspect that you used the `start` command without entering any phone number or name. You should use it like this: `start <number with country code or name>` For example: `start g0dev` or `start 18001234567`

**Comment by FKLC** [comment]
If that is the case the latest release will not crash but tell the correct usage of the command.

**Comment by g0dev** [comment]
Ye, it was the problem. It works for a few hours, but now when i send a message it crash. I just update to the new release, and the start command didnt work. Im using the same number that i used with the previous version and doesnt work.
![image](https://user-images.githubusercontent.com/55219735/87815899-0b2f8000-c82c-11ea-9a72-b32efc397ca6.png)
Also tried with all posibble combinations

**Comment by FKLC** [comment]
Welp, I made a horrible mistake in the if comparison but now it should be working. Please download the latest release and try again. 

Note: I've deleted the old commit as it could confuse people.

**Comment by g0dev** [comment]
now works, ty.
Will been testing it
