### ISSUE TITLE
Whitelist not working

### ISSUE THREAD

**Issue by S0FLGotTaken** [FKLC/WhatsAppToDiscord#81]
I whitelisted 3 channels on my discord but new ones keep coming up as I talk on WhatsApp. How can I limit the channels that get synced with dc?

New channels appear when I send a message on Whatsapp, not the other way around.

**Comment by S0FLGotTaken** [comment]
I did that and it didn't work. When I do listWhitelist it shows the 3 channels but new ones keep popping up as I send messages

**Comment by FKLC** [comment]
Fixed this issue. Please see the latest version. Feel free to reopen if needed.
