### ISSUE TITLE
Bot crashes when sending file without a message in Whatsapp

### ISSUE THREAD

**Issue by Arkanista** [FKLC/WhatsAppToDiscord#9]
Whenever a picture or a file containing no additional message is sent in whatsapp the bot crashes:

panic: HTTP 400 Bad Request, {"message": "Cannot send an empty message", "code": 50006}

goroutine 55 [running]:
main.handleMediaMessage(0xc0001fc600, 0x14, 0xc0001fc5e0, 0x1b, 0x0, 0x0, 0x0, 0x5f2134e2, 0x0, 0x0, ...)
        command-line-arguments/WA2DC.go:338 +0x2e0
main.waHandler.HandleDocumentMessage(0xc0001fc600, 0x14, 0xc0001fc5e0, 0x1b, 0x0, 0x0, 0x0, 0x5f2134e2, 0x0, 0x0, ...)
        command-line-arguments/WA2DC.go:372 +0x121
created by github.com/Rhymen/go-whatsapp.(*Conn).handleWithCustomHandlers
        github.com/Rhymen/go-whatsapp@v0.1.0/handler.go:242 +0xdb1

While I understand the bot doesn't send pictures or files, maybe it should at least not crash at this event or send a message saying [file]

**Comment by FKLC** [comment]
Latest release should fix it. If it is still not working feel free to reopen the issue
