### ISSUE TITLE
Reply to a message make the bot crash

### ISSUE THREAD

**Issue by Nerodacles** [FKLC/WhatsAppToDiscord#90]
If i reply the bot on discord, it will crash.

**Comment by FKLC** [comment]
Unfortunately, I can't reproduce the bug on my end. Could you reproduce the bug and send your logs.txt?

**Comment by Nerodacles** [comment]
Ok, give me a moment.

**Comment by Nerodacles** [comment]
[logs.txt](https://github.com/FKLC/WhatsAppToDiscord/files/9438643/logs.txt)

**Comment by FKLC** [comment]
Okay I deleted your logs for privacy reasons, and fixed the issue. However, on further research, I found quoted messages only work on the client device, and not on the receiving end (for messages sent from discord to whatsapp). So, I won't push a new update yet and keep this issue, as I fix the other bug I mentioned above.

**Comment by Nerodacles** [comment]
Thank You!

**Comment by FKLC** [comment]
I pushed a partial update (so the bot won't crash), but know that the replied message won't show up on the other device.

**Comment by FKLC** [comment]
Everything should be working now.
