### ISSUE TITLE
Emotion Reactions

### ISSUE THREAD

**Issue by spookycookie27** [FKLC/WhatsAppToDiscord#93]
Great Update!

I notice that if users  repeat the same reaction in WA (a 2nd thumbs up or repeat of another) It doesnt get sent to Discord, you only see the first..

But great work, thank you FKLC!

**Comment by FKLC** [comment]
Yeah, unfortunately it isn't really possible to double react using just one bot. A bot can only react once and there is no way of increasing the counter. I'm closing this issue as there is no possible solution.

**Comment by f-wllr** [comment]
Hey, I really like your project, but might it be possible that the bot creates a thread with all reactions? So for each message someone has reacted to, there's a thread with all reactions from WhatsApp were also the names could be transferred.

I have read this issue a few days ago and today this idea came in my head.
