### ISSUE TITLE
WA2DC-Linux down  (from release builds 30-08) after send image from Discord

### ISSUE THREAD

**Issue by magadan** [FKLC/WhatsAppToDiscord#95]
**Describe the bug**
WA2DC-Linuxdown after send image from Discord

**To Reproduce**

1. Go to the channel conversantion and sent a image...
4. The WA2DC-Linux simply stops, no error on console only in logs.txt.

**Expected behavior**

**Logs**
{"level":50,"time":1661913904169,"pid":115806,"hostname":"suporte","err":{"type":"TypeError","message":"object is not iterable (cannot read property Symbol(Symbol.iterator))","stack":"TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))\n    at /snapshot/WhatsAppToDiscord/src/whatsapp_manager.js:97:49\n    at /snapshot/WhatsAppToDiscord/node_modules/@discordjs/collection/dist/index.js:182:14\n    at Function.from (<anonymous>)\n    at _Collection.map (/snapshot/WhatsAppToDiscord/node_modules/@discordjs/collection/dist/index.js:180:18)\n    at EventEmitter.<anonymous> (/snapshot/WhatsAppToDiscord/src/whatsapp_manager.js:97:45)\n    at EventEmitter.emit (node:events:527:28)\n    at EventEmitter.<anonymous> (/snapshot/WhatsAppToDiscord/node_modules/@adiwajshing/baileys/lib/Utils/event-buffer.js:38:16)\n    at EventEmitter.emit (node:events:527:28)\n    at Object.emit (/snapshot/WhatsAppToDiscord/node_modules/@adiwajshing/baileys/lib/Utils/event-buffer.js:56:23)\n    at Client.<anonymous> (/snapshot/WhatsAppToDiscord/src/discord_manager.js:241:23)"},"msg":"object is not iterable (cannot read property Symbol(Symbol.iterator))"}
{"level":30,"time":1661913904169,"pid":115806,"hostname":"suporte","msg":"Exiting!"}
{"level":30,"time":1661913904179,"pid":115806,"hostname":"suporte","msg":"Exiting!"}

**Platform**
Linux

**Additional context**
Im using latest release for linux downloaded last hour.

**Comment by FKLC** [comment]
Fixed it. New version should be released in a few minutes.

**Comment by magadan** [comment]
Thank you! Its working.
