### ISSUE TITLE
Builds for Linux 32, Aarch64 and Armv7

### ISSUE THREAD

**Issue by magadan** [FKLC/WhatsAppToDiscord#96]
Hello, its possible to you include builds for 

Linux 32 bits
Aarch64
Armv7

thanks

**Comment by FKLC** [comment]
Unfortunately, it is not possible. Pkg is the package that is used for compilation, and it doesn't support any of the archs you list there. I'm sorry.

**Comment by magadan** [comment]
ok ! thank u.
