### ISSUE TITLE
Voice call Feature request

### ISSUE THREAD

**Issue by borjita2019** [FKLC/WhatsAppToDiscord#97]
**Is your feature request related to a problem? Please describe.**
Isn't related.

**Describe the solution you'd like**
I want a voice call bridge to discord so my discord friends can talk on whatsapp while my whatsapp friends talk on discord, if it's even possible

**Describe alternatives you've considered**
No alternatives.

**Comment by FKLC** [comment]
Unfortunately, it isn't possible. This project is dependent on [Baileys](https://github.com/adiwajshing/Baileys) and they are pretty much dependent on [@sigalor's](https://github.com/sigalor/whatsapp-web-reveng) research. I checked both of the projects, and voice or video call isn't supported yet.
